<a href="https://colab.research.google.com/github/preethisedigar/data_analytics_projects/blob/main/Australia_Weather_Data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## CASE STUDY : Australia Weather Data

This notebook will cover the following topics:
* Filtering dataframes
* Single and multiple conditions
* Creating new columns
* Lambda functions
* Group by and aggregate functions
* Pivot data
* Merging data frames
* Joins and concatenations

### Background
An FMCG company P&J found that the sales of their best selling items are affected by the weather and rainfall trend. For example, the sale of tea increases when it rains, sunscreen is sold on the days when it is least likely to rain, and the sky is clear. They would like to check whether the weather patterns play a vital role in the sale of certain items. Hence as initial experimentation, they would like you to forecast the weather trend in the upcoming days. The target region for this activity is Australia; accordingly, this exercise will be based on analysing and cleaning the weather data from the Australian region available on public platforms.

### Data Dictionary
1. Date: The date on which the recording was taken
2. Location: The location of the recording
3. MinTemp: Minimum temperature on the day of the recording (in C)
4. MaxTemp: Maximum temperature in the day of the recording (in C)
5. Rainfall: Rainfall in mm
6. Evaporation: The so-called Class A pan evaporation (mm) in the 24 hours to 9am
7. Sunshine: The number of hours of bright sunshine in the day.
8. WindGustDir: The direction of the strongest wind gust in the 24 hours to midnight
9. WindGustSpeed: The speed (km/h) of the strongest wind gust in the 24 hours to midnight

In [ ]:
# importing necesary library
import numpy as np , pandas as pd

In [ ]:
#Read the data into a dataframe
data = pd.read_csv("weatherdata.csv")
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

## Data Inspection

In [ ]:
data.shape

(142193, 9)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  object
 1   Location       142193 non-null  object
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object
 8   WindGustSpeed  132923 non-null  float64
dtypes: float64(6), object(3)
memory usage: 9.8+ MB

In [ ]:
data.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
dtype: int64

In [ ]:
# percentage of null rows in each columns
round((data.isnull().sum()/len(data))*100,2)

Date              0.00
Location          0.00
MinTemp           0.45
MaxTemp           0.23
Rainfall          0.99
Evaporation      42.79
Sunshine         47.69
WindGustDir       6.56
WindGustSpeed     6.52
dtype: float64

### Filtering dataframes
Find the days which had sunshine for more that 4 hours. These days will have increased sales of sunscreen.

**Note:** High sunshine corresponds to low rainfall.

In [ ]:
# filtering

data[data['Sunshine'] > 4]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5940,2009-01-02,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0
5941,2009-01-03,Cobar,15.5,34.1,0.0,12.6,13.3,SE,30.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
...,...,...,...,...,...,...,...,...,...
139108,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [ ]:
data[data['Location'] == 'Darwin']

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
135921,2008-07-01,Darwin,20.0,33.1,0.0,4.4,11.0,E,41.0
135922,2008-07-02,Darwin,19.4,32.4,0.0,6.0,10.4,ENE,50.0
135923,2008-07-03,Darwin,18.2,31.8,0.0,8.0,11.0,E,46.0
135924,2008-07-04,Darwin,17.3,30.7,0.0,7.0,10.4,E,44.0
135925,2008-07-05,Darwin,15.5,30.8,0.0,7.0,10.8,ESE,46.0
...,...,...,...,...,...,...,...,...,...
139108,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [ ]:
data[data['Rainfall'] > 35]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
429,2010-02-05,Albury,19.2,26.1,52.2,NaN,NaN,SE,33.0
455,2010-03-08,Albury,18.1,25.5,66.0,NaN,NaN,NW,56.0
690,2010-10-31,Albury,13.8,18.7,50.8,NaN,NaN,NNW,52.0
704,2010-11-14,Albury,19.2,22.6,52.6,NaN,NaN,N,26.0
787,2011-02-05,Albury,20.4,23.0,99.2,NaN,NaN,NW,28.0
...,...,...,...,...,...,...,...,...,...
140752,2013-05-21,Uluru,16.6,22.3,42.4,NaN,NaN,N,39.0
141783,2016-05-08,Uluru,16.3,21.9,39.0,NaN,NaN,W,35.0
141830,2016-06-26,Uluru,10.2,15.6,42.0,NaN,NaN,SSW,43.0
142013,2016-12-26,Uluru,22.1,27.4,83.8,NaN,NaN,ENE,72.0
142014,2016-12-27,Uluru,22.1,35.8,63.8,NaN,NaN,WNW,43.0

### The cold drink sales will most likely increase on the days which have high sunshine(>5) and high max temperature(>35). Use the filter operation to filter out these days

In [ ]:
data[(data['Rainfall'] > 35)  & (data['Sunshine'] > 5)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
8972,2009-02-15,CoffsHarbour,18.3,24.8,38.6,3.4,6.2,SW,57.0
8988,2009-03-03,CoffsHarbour,20.7,27.3,36.6,5.8,5.2,SSW,24.0
9238,2009-11-09,CoffsHarbour,17.8,23.4,58.0,NaN,6.1,NaN,NaN
9324,2010-02-03,CoffsHarbour,20.9,28.0,67.0,NaN,6.0,NE,41.0
9792,2011-06-16,CoffsHarbour,11.3,18.4,63.2,NaN,6.2,SW,52.0
...,...,...,...,...,...,...,...,...,...
138265,2015-02-28,Darwin,23.0,31.8,68.6,NaN,7.1,WNW,43.0
138696,2016-05-04,Darwin,24.2,32.1,47.4,7.8,5.6,NE,35.0
138896,2016-11-20,Darwin,21.2,32.7,41.0,11.6,5.9,SSE,43.0
138929,2016-12-23,Darwin,23.3,33.5,37.2,5.2,8.8,NNW,37.0
138995,2017-02-27,Darwin,24.2,33.7,49.2,NaN,10.8,ENE,33.0

In [ ]:
data[(data['Rainfall'] > 35)  | (data['Sunshine'] > 4)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
429,2010-02-05,Albury,19.2,26.1,52.2,NaN,NaN,SE,33.0
455,2010-03-08,Albury,18.1,25.5,66.0,NaN,NaN,NW,56.0
690,2010-10-31,Albury,13.8,18.7,50.8,NaN,NaN,NNW,52.0
704,2010-11-14,Albury,19.2,22.6,52.6,NaN,NaN,N,26.0
787,2011-02-05,Albury,20.4,23.0,99.2,NaN,NaN,NW,28.0
...,...,...,...,...,...,...,...,...,...
140752,2013-05-21,Uluru,16.6,22.3,42.4,NaN,NaN,N,39.0
141783,2016-05-08,Uluru,16.3,21.9,39.0,NaN,NaN,W,35.0
141830,2016-06-26,Uluru,10.2,15.6,42.0,NaN,NaN,SSW,43.0
142013,2016-12-26,Uluru,22.1,27.4,83.8,NaN,NaN,ENE,72.0
142014,2016-12-27,Uluru,22.1,35.8,63.8,NaN,NaN,WNW,43.0

In [ ]:
data[(data['Evaporation'] > 35)  | (data['Sunshine'] > 4)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5940,2009-01-02,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0
5941,2009-01-03,Cobar,15.5,34.1,0.0,12.6,13.3,SE,30.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
...,...,...,...,...,...,...,...,...,...
139108,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [ ]:
data[(data['WindGustDir'] == 'E') & (data['Rainfall'] > 40) & (data['MinTemp'] > 10)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
4060,2012-01-26,BadgerysCreek,19.5,27.3,61.4,NaN,NaN,E,41.0
4143,2012-04-19,BadgerysCreek,16.9,25.2,82.4,NaN,NaN,E,24.0
8974,2009-02-17,CoffsHarbour,19.9,27.1,189.0,NaN,4.9,E,54.0
9096,2009-06-20,CoffsHarbour,12.7,19.2,70.0,NaN,1.6,E,37.0
9566,2010-10-03,CoffsHarbour,15.3,18.7,90.0,NaN,0.0,E,50.0
...,...,...,...,...,...,...,...,...,...
137568,2013-04-02,Darwin,23.6,29.7,92.6,NaN,0.2,E,50.0
137785,2013-11-05,Darwin,21.3,33.2,105.0,NaN,7.7,E,31.0
138292,2015-03-27,Darwin,22.8,29.4,102.2,NaN,0.9,E,41.0
138525,2015-11-15,Darwin,22.0,33.0,44.6,12.6,4.8,E,50.0
139142,2013-03-30,Katherine,24.0,25.8,63.4,NaN,NaN,E,28.0

### If you noticed the filtering done in the earlier examples did not give precise information about the days, the data column simply has the dates. The date column can be split into the year, month and day of the month.

In [ ]:
pd.to_datetime(data['Date']).dt.year.value_counts()

Date
2016    17508
2014    17400
2015    17231
2009    16595
2010    16419
2013    16097
2011    15126
2012    15044
2017     8466
2008     2246
2007       61
Name: count, dtype: int64

In [ ]:
pd.to_datetime(data['Date']).dt.month.value_counts()

Date
5     13055
3     13036
1     12921
6     12389
10    11804
7     11779
8     11762
11    11461
9     11345
4     11306
12    10810
2     10525
Name: count, dtype: int64

In [ ]:
pd.to_datetime(data['Date']).dt.day.value_counts()

Date
1     4688
15    4688
16    4687
13    4686
2     4686
6     4684
22    4684
3     4683
12    4682
7     4680
21    4677
14    4677
19    4676
20    4675
4     4674
23    4672
9     4672
17    4671
8     4671
11    4668
5     4667
24    4666
25    4665
18    4665
10    4664
26    4637
28    4630
27    4627
29    4374
30    4280
31    2737
Name: count, dtype: int64

### **Adding New columns** To add a new column in the dataframe just name the column and pass the instructions about the creation of the new column

In [ ]:
data['Year'] = pd.to_datetime(data['Date']).dt.year
data['Month'] = pd.to_datetime(data['Date']).dt.month
data['Day'] = pd.to_datetime(data['Date']).dt.day

In [ ]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12,4
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12,5

### The temperature given is in Celcius, convert it in Fahrenheit and store it in a new column for it.

In [ ]:
data['MaxTemp_F'] = data['MaxTemp'] * 9/5 + 32

In [ ]:
data['MinTemp_F'] = data['MinTemp'] * 9/5 + 32
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1,73.22,56.12
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2,77.18,45.32
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3,78.26,55.22
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12,4,82.40,48.56
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12,5,90.14,63.50

### Let's create a new column which highlights the days which have rainfall more than 50 mm as rainy days and the rest are not.

**Note**
1.  New way of accessing a column in a dataframe by using the dot operator.
2. "apply" function takes in a lambda operator as argument.

In [ ]:
# check Rainfall

data['RainFall_Check'] = data.Rainfall.apply(lambda x: "Rainy" if x > 50 else "Not Rainy")
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1,73.22,56.12,Not Rainy
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2,77.18,45.32,Not Rainy
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3,78.26,55.22,Not Rainy
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12,4,82.40,48.56,Not Rainy
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12,5,90.14,63.50,Not Rainy

In [ ]:
type('RainFall_Check')

str

In [ ]:
type('MaxTemp_F')

str

In [ ]:
type('MinTemp_F')

str

In [ ]:
data[data['RainFall_Check'] == 'Rainy']

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check
429,2010-02-05,Albury,19.2,26.1,52.2,NaN,NaN,SE,33.0,2010,2,5,78.98,66.56,Rainy
455,2010-03-08,Albury,18.1,25.5,66.0,NaN,NaN,NW,56.0,2010,3,8,77.90,64.58,Rainy
690,2010-10-31,Albury,13.8,18.7,50.8,NaN,NaN,NNW,52.0,2010,10,31,65.66,56.84,Rainy
704,2010-11-14,Albury,19.2,22.6,52.6,NaN,NaN,N,26.0,2010,11,14,72.68,66.56,Rainy
787,2011-02-05,Albury,20.4,23.0,99.2,NaN,NaN,NW,28.0,2011,2,5,73.40,68.72,Rainy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140532,2017-02-03,Katherine,23.4,33.0,62.0,NaN,NaN,NNW,33.0,2017,2,3,91.40,74.12,Rainy
140571,2017-03-14,Katherine,23.0,35.0,79.0,31.0,NaN,ESE,22.0,2017,3,14,95.00,73.40,Rainy
140578,2017-03-22,Katherine,24.1,34.5,61.4,NaN,NaN,N,31.0,2017,3,22,94.10,75.38,Rainy
142013,2016-12-26,Uluru,22.1,27.4,83.8,NaN,NaN,ENE,72.0,2016,12,26,81.32,71.78,Rainy
142014,2016-12-27,Uluru,22.1,35.8,63.8,NaN,NaN,WNW,43.0,2016,12,27,96.44,71.78,Rainy

### Grouping and Aggregate functions
Find the location which received the most amount of rain in the given data. In this place, certain promotional offers can be put in place to boost sales of tea, umbrella etc.

In [ ]:
# Groupby Functions

data.groupby(['Location'])['Rainfall'].mean()

Location
Adelaide            1.572185
Albany              2.255073
Albury              1.925710
AliceSprings        0.869355
BadgerysCreek       2.207925
Ballarat            1.688830
Bendigo             1.621452
Brisbane            3.160536
Cairns              5.765317
Canberra            1.735038
Cobar               1.129262
CoffsHarbour        5.054592
Dartmoor            2.148554
Darwin              5.094048
GoldCoast           3.728933
Hobart              1.604273
Katherine           3.135599
Launceston          2.012219
Melbourne           1.837772
MelbourneAirport    1.451977
Mildura             0.945025
Moree               1.603296
MountGambier        2.087359
MountGinini         3.245241
Newcastle           3.153022
Nhil                0.932907
NorahHead           3.382479
NorfolkIsland       3.137568
Nuriootpa           1.381375
PearceRAAF          1.634354
Penrith             2.135143
Perth               1.906295
PerthAirport        1.761648
Portland            2.531032
Richmond            2.152581
Sale                1.512667
SalmonGums          1.032302
Sydney              3.330231
SydneyAirport       2.995335
Townsville          3.488603
Tuggeranong         2.159040
Uluru               0.707324
WaggaWagga          1.706085
Walpole             2.877329
Watsonia            1.847692
Williamtown         3.510985
Witchcliffe         2.899658
Wollongong          3.589127
Woomera             0.489946
Name: Rainfall, dtype: float64

In [ ]:
# To see which city has the highest average rainfall
data.groupby(['Location'])['Rainfall'].mean().sort_values(ascending = False)

Location
Cairns              5.765317
Darwin              5.094048
CoffsHarbour        5.054592
GoldCoast           3.728933
Wollongong          3.589127
Williamtown         3.510985
Townsville          3.488603
NorahHead           3.382479
Sydney              3.330231
MountGinini         3.245241
Brisbane            3.160536
Newcastle           3.153022
NorfolkIsland       3.137568
Katherine           3.135599
SydneyAirport       2.995335
Witchcliffe         2.899658
Walpole             2.877329
Portland            2.531032
Albany              2.255073
BadgerysCreek       2.207925
Tuggeranong         2.159040
Richmond            2.152581
Dartmoor            2.148554
Penrith             2.135143
MountGambier        2.087359
Launceston          2.012219
Albury              1.925710
Perth               1.906295
Watsonia            1.847692
Melbourne           1.837772
PerthAirport        1.761648
Canberra            1.735038
WaggaWagga          1.706085
Ballarat            1.688830
PearceRAAF          1.634354
Bendigo             1.621452
Hobart              1.604273
Moree               1.603296
Adelaide            1.572185
Sale                1.512667
MelbourneAirport    1.451977
Nuriootpa           1.381375
Cobar               1.129262
SalmonGums          1.032302
Mildura             0.945025
Nhil                0.932907
AliceSprings        0.869355
Uluru               0.707324
Woomera             0.489946
Name: Rainfall, dtype: float64

### Hot chocolate is the most sold product in the cold months. Find month which is the coldest so that the inventory team can keep the stock of hot chocolate ready well in advance.

In [ ]:
data.groupby(['Location','Month'])['Rainfall'].mean().sort_values(ascending = False)

Location    Month
Cairns      2        16.769912
Darwin      2        16.736283
            1        14.627240
Cairns      1        13.814337
Townsville  2        11.550000
                       ...
Darwin      8         0.010036
            6         0.003788
            7         0.000717
Katherine   6         0.000699
            8         0.000000
Name: Rainfall, Length: 588, dtype: float64

In [ ]:
data.groupby(['Location', 'Month'])['MaxTemp'].median().sort_values(ascending = False)

Location     Month
Katherine    11       39.40
             10       38.60
Uluru        2        38.30
             1        37.70
             12       37.60
                      ...
MountGinini  9         9.10
             5         7.55
             6         4.20
             8         3.90
             7         2.60
Name: MaxTemp, Length: 588, dtype: float64

### Sometimes feeling cold is more than about low temperatures; a windy day can also make you cold. A factor called the chill factor can be used to quantify the cold based on the wind speed and the temperature. The formula for the chill factor is given by

$ WCI = (10 * \sqrt{v} - v + 10.5) .(33 - T_{m}) $

v is the speed of the wind and

$ T_{m} $ is the minimum temperatur
e
Add a column for WCI and find the month with the lowest WCI.
CI.

In [ ]:
# creating a new column in data using def function
from math import sqrt
def wci(x): # WCI Wind chill Index
    veclocity = x['WindGustSpeed']
    mintemp = x['MinTemp']
    return((10 * sqrt(veclocity) - veclocity + 10.5) * 33 - mintemp)

In [ ]:
data['WCI'] = data.apply(wci, axis = 1)
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check,WCI
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1,73.22,56.12,Not Rainy,1070.072362
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2,77.18,45.32,Not Rainy,1076.072362
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3,78.26,55.22,Not Rainy,1053.768894
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12,4,82.40,48.56,Not Rainy,1161.963230
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12,5,90.14,63.50,Not Rainy,1089.030998

In [ ]:
# reading the remaining files

sales = pd.read_csv('junesales.csv')
sales.head()

       Date  Tea_sales(in 100's)
0  6/1/2011                   26
1  6/2/2011                   35
2  6/3/2011                   37
3  6/4/2011                   33
4  6/5/2011                   25

In [ ]:
location = pd.read_csv('locationsandstates.csv')
location.head()

         Location             State
0          Sydney  New South Wales
1          Albury  New South Wales
2        Armidale  New South Wales
3        Bathurst  New South Wales
4  Blue Mountains  New South Wales

In [ ]:
sales['Day'] = pd.to_datetime(sales['Date']).dt.day
sales.head()

       Date  Tea_sales(in 100's)  Day
0  6/1/2011                   26    1
1  6/2/2011                   35    2
2  6/3/2011                   37    3
3  6/4/2011                   33    4
4  6/5/2011                   25    5

In [ ]:
# creating a subset of the data
newdata = data[(data['Year'] == 2011) & (data['Month'] == 6)]
newdata.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check,WCI
873,2011-06-01,Albury,3.1,19.8,0.0,NaN,NaN,NE,17.0,2011,6,1,67.64,37.58,Not Rainy,1143.024856
874,2011-06-02,Albury,2.9,17.6,0.0,NaN,NaN,N,15.0,2011,6,2,63.68,37.22,Not Rainy,1126.684504
875,2011-06-03,Albury,4.3,18.3,0.0,NaN,NaN,NW,20.0,2011,6,3,64.94,39.74,Not Rainy,1158.004865
876,2011-06-04,Albury,8.5,14.8,8.8,NaN,NaN,W,24.0,2011,6,4,58.64,47.30,Not Rainy,1162.663230
877,2011-06-05,Albury,2.2,12.0,0.0,NaN,NaN,N,28.0,2011,6,5,53.60,35.96,Not Rainy,1166.495865

In [ ]:
newdata.shape

(1348, 16)

### The join command is used to combine dataframes. Unlike hstack and vstack, the join command works by using a key to combine to dataframes.

##### Types of joins.

* INNER JOIN
* LEFT JOIN
* RIGHT JOIN
* FULLame.

In [ ]:
newdata = newdata.merge(sales, on = 'Day', how = 'left')
newdata

,Date_x,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check,WCI,Date_y,Tea_sales(in 100's)
0,2011-06-01,Albury,3.1,19.8,0.0,NaN,NaN,NE,17.0,2011,6,1,67.64,37.58,Not Rainy,1143.024856,6/1/2011,26
1,2011-06-02,Albury,2.9,17.6,0.0,NaN,NaN,N,15.0,2011,6,2,63.68,37.22,Not Rainy,1126.684504,6/2/2011,35
2,2011-06-03,Albury,4.3,18.3,0.0,NaN,NaN,NW,20.0,2011,6,3,64.94,39.74,Not Rainy,1158.004865,6/3/2011,37
3,2011-06-04,Albury,8.5,14.8,8.8,NaN,NaN,W,24.0,2011,6,4,58.64,47.30,Not Rainy,1162.663230,6/4/2011,33
4,2011-06-05,Albury,2.2,12.0,0.0,NaN,NaN,N,28.0,2011,6,5,53.60,35.96,Not Rainy,1166.495865,6/5/2011,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1343,2011-06-26,Darwin,19.5,32.6,0.0,5.0,10.9,E,39.0,2011,6,26,90.68,67.10,Not Rainy,1100.849339,6/26/2011,42
1344,2011-06-27,Darwin,18.0,29.8,0.0,7.4,10.9,E,30.0,2011,6,27,85.64,64.40,Not Rainy,1145.984440,6/27/2011,24
1345,2011-06-28,Darwin,17.0,29.5,0.0,4.6,11.0,E,39.0,2011,6,28,85.10,62.60,Not Rainy,1103.349339,6/28/2011,46
1346,2011-06-29,Darwin,16.4,30.3,0.0,6.0,10.1,E,33.0,2011,6,29,86.54,61.52,Not Rainy,1136.805673,6/29/2011,48
1347,2011-06-30,Darwin,18.1,31.6,0.0,4.4,10.7,ESE,33.0,2011,6,30,88.88,64.58,Not Rainy,1135.105673,6/30/2011,40

In [ ]:
newdata = newdata.merge(location, on = 'Location', how = 'left')
newdata

NameError: name 'newdata' is not defined

In [ ]:
newdata.columns

Index(['Date_x', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'Year', 'Month', 'Day',
       'MaxTemp_F', 'MinTemp_F', 'RainFall_Check', 'WCI', 'Date_y',
       'Tea_sales(in 100's)', 'State'],
      dtype='object')

In [ ]:
newdata.rename(columns = {'Tea_sales(in 100\'s)': 'TeaSalesinhundreds'}, inplace = True)

In [ ]:
# this will contain 2011 June data only
final_data = newdata[['State','Location', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'Year', 'Month', 'Day',
       'MaxTemp_F', 'MinTemp_F', 'RainFall_Check', 'WCI', 'TeaSalesinhundreds']]

In [ ]:
final_data.head()

,State,Location,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check,WCI,TeaSalesinhundreds
0,New South Wales,Albury,0.0,NaN,NaN,NE,17.0,2011,6,1,67.64,37.58,Not Rainy,1143.024856,26
1,New South Wales,Albury,0.0,NaN,NaN,N,15.0,2011,6,2,63.68,37.22,Not Rainy,1126.684504,35
2,New South Wales,Albury,0.0,NaN,NaN,NW,20.0,2011,6,3,64.94,39.74,Not Rainy,1158.004865,37
3,New South Wales,Albury,8.8,NaN,NaN,W,24.0,2011,6,4,58.64,47.30,Not Rainy,1162.663230,33
4,New South Wales,Albury,0.0,NaN,NaN,N,28.0,2011,6,5,53.60,35.96,Not Rainy,1166.495865,25

In [ ]:
newdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1348 entries, 0 to 1347
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date_x              1348 non-null   object
 1   Location            1348 non-null   object
 2   MinTemp             1338 non-null   float64
 3   MaxTemp             1346 non-null   float64
 4   Rainfall            1331 non-null   float64
 5   Evaporation         864 non-null    float64
 6   Sunshine            822 non-null    float64
 7   WindGustDir         1273 non-null   object
 8   WindGustSpeed       1273 non-null   float64
 9   Year                1348 non-null   int32
 10  Month               1348 non-null   int32
 11  Day                 1348 non-null   int32
 12  MaxTemp_F           1346 non-null   float64
 13  MinTemp_F           1338 non-null   float64
 14  RainFall_Check      1348 non-null   object
 15  WCI                 1271 non-null   float64
 16  Date_y              1348 non-null   object
 17  TeaSalesinhundreds  1348 non-null   int64
 18  State               561 non-null    object
dtypes: float64(9), int32(3), int64(1), object(6)
memory usage: 184.4+ KB

In [ ]:
# Creating pivot tables

table1 = newdata.pivot_table(index = 'Location', columns = ['RainFall_Check'], values = 'TeaSalesinhun' , aggfunc = 'mean')
table1dreds

RainFall_Check    Not Rainy      Rainy
Location
Adelaide          35.034483        NaN
Albany            34.966667        NaN
Albury            34.966667        NaN
AliceSprings      34.966667        NaN
BadgerysCreek     34.966667        NaN
Ballarat          34.966667        NaN
Bendigo           34.966667        NaN
Brisbane          34.689655        NaN
Cairns            34.517241  48.000000
Canberra          34.964286        NaN
Cobar             34.966667        NaN
CoffsHarbour      35.111111  33.666667
Dartmoor          34.966667        NaN
Darwin            34.966667        NaN
GoldCoast         34.966667        NaN
Hobart            34.966667        NaN
Launceston        34.966667        NaN
Melbourne         35.363636        NaN
MelbourneAirport  34.966667        NaN
Mildura           34.966667        NaN
Moree             34.966667        NaN
MountGambier      34.966667        NaN
MountGinini       34.807692        NaN
Newcastle         34.966667        NaN
NorahHead         35.071429  34.000000
NorfolkIsland     34.966667        NaN
Nuriootpa         34.966667        NaN
PearceRAAF        36.038462        NaN
Penrith           34.966667        NaN
Perth             35.206897  28.000000
PerthAirport      34.966667        NaN
Portland          34.966667        NaN
Richmond          34.966667        NaN
Sale              34.966667        NaN
SalmonGums        34.966667        NaN
Sydney            34.966667        NaN
SydneyAirport     34.966667        NaN
Townsville        34.966667        NaN
Tuggeranong       34.966667        NaN
WaggaWagga        34.966667        NaN
Walpole           34.966667        NaN
Watsonia          34.966667        NaN
Williamtown       35.000000  34.000000
Witchcliffe       34.966667        NaN
Wollongong        35.275862  26.000000
Woomera           34.966667        NaN

### Each state may have different tax laws, so we might want to add the states information to the data as well.

In [ ]:
table2 = newdata.pivot_table(index = ['State','Location'], columns = ['RainFall_Check'], values = 'TeaSalesinhundreds' , aggfunc = 'mean')
table2

RainFall_Check                 Not Rainy  Rainy
State              Location
New South Wales    Albury      34.966667    NaN
                   Newcastle   34.966667    NaN
                   Penrith     34.966667    NaN
                   Sydney      34.966667    NaN
                   WaggaWagga  34.966667    NaN
                   Wollongong  35.275862   26.0
Northern Territory Darwin      34.966667    NaN
Queensland         Brisbane    34.689655    NaN
                   Cairns      34.517241   48.0
                   Townsville  34.966667    NaN
Tasmania           Hobart      34.966667    NaN
                   Launceston  34.966667    NaN
Victoria           Ballarat    34.966667    NaN
                   Bendigo     34.966667    NaN
                   Melbourne   35.363636    NaN
                   Mildura     34.966667    NaN
                   Sale        34.966667    NaN
Western Australia  Albany      34.966667    NaN
                   Perth       35.206897   28.0

In [ ]:
newdata1 = newdata[newdata['State'] == 'Western Australia']
table3 = newdata1.pivot_table(index = 'State', columns = ['RainFall_Check'], values = 'TeaSalesinhundreds' , aggfunc = 'mean')
table3

NameError: name 'newdata' is not defined

In [ ]:
table4 = newdata.pivot_table(index = ['State','Location'], columns = ['RainFall_Check'], values = ['TeaSalesinhundreds','MaxTemp_F'], aggfunc = 'mean')
table4

                               MaxTemp_F        TeaSalesinhundreds
RainFall_Check                 Not Rainy  Rainy          Not Rainy Rainy
State              Location
New South Wales    Albury      58.136000    NaN          34.966667   NaN
                   Newcastle   65.198000    NaN          34.966667   NaN
                   Penrith     64.100000    NaN          34.966667   NaN
                   Sydney      64.460000    NaN          34.966667   NaN
                   WaggaWagga  58.496000    NaN          34.966667   NaN
                   Wollongong  63.301379  64.22          35.275862  26.0
Northern Territory Darwin      84.236000    NaN          34.966667   NaN
Queensland         Brisbane    69.800000    NaN          34.689655   NaN
                   Cairns      79.066897  78.26          34.517241  48.0
                   Townsville  76.610000    NaN          34.966667   NaN
Tasmania           Hobart      55.766000    NaN          34.966667   NaN
                   Launceston  55.844000    NaN          34.966667   NaN
Victoria           Ballarat    52.916000    NaN          34.966667   NaN
                   Bendigo     58.100000    NaN          34.966667   NaN
                   Melbourne   60.570909    NaN          35.363636   NaN
                   Mildura     62.750000    NaN          34.966667   NaN
                   Sale        58.916000    NaN          34.966667   NaN
Western Australia  Albany      64.712000    NaN          34.966667   NaN
                   Perth       67.180690  66.56          35.206897  28.0

Using pivot tables find the average monthly rainfall in the year 2016 of all the locations. The information can then be used to predict the sales of tea in the year 2017.

In [ ]:
data_2016 = data[data['Year'] == 2016]
data_2016

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Day,MaxTemp_F,MinTemp_F,RainFall_Check,WCI
2474,2016-01-01,Albury,20.4,37.6,0.0,NaN,NaN,ENE,54.0,2016,1,1,99.68,68.72,Not Rainy,969.094845
2475,2016-01-02,Albury,20.9,33.6,0.4,NaN,NaN,SSE,50.0,2016,1,2,92.48,69.62,Not Rainy,1009.052378
2476,2016-01-03,Albury,18.4,23.1,2.2,NaN,NaN,ENE,48.0,2016,1,3,73.58,65.12,Not Rainy,1030.407066
2477,2016-01-04,Albury,17.3,23.7,15.6,NaN,NaN,SSE,39.0,2016,1,4,74.66,63.14,Not Rainy,1103.049339
2478,2016-01-05,Albury,15.5,22.9,6.8,NaN,NaN,ENE,31.0,2016,1,5,73.22,59.90,Not Rainy,1145.362240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142014,2016-12-27,Uluru,22.1,35.8,63.8,NaN,NaN,WNW,43.0,2016,12,27,96.44,71.78,Rainy,1069.354713
142015,2016-12-28,Uluru,22.6,36.8,0.0,NaN,NaN,NW,50.0,2016,12,28,98.24,72.68,Not Rainy,1007.352378
142016,2016-12-29,Uluru,23.2,38.0,0.0,NaN,NaN,SSW,33.0,2016,12,29,100.40,73.76,Not Rainy,1130.005673
142017,2016-12-30,Uluru,19.7,37.0,0.0,NaN,NaN,E,37.0,2016,12,30,98.60,67.46,Not Rainy,1113.111635
142018,2016-12-31,Uluru,23.7,33.0,0.0,NaN,NaN,NE,46.0,2016,12,31,91.40,74.66,Not Rainy,1042.968894

In [ ]:
data_2016.pivot_table(index = 'Location', columns = 'Month', values = 'Rainfall', aggfunc = 'mean')

Month,1,2,3,4,5,6,7,8,9,10,11,12
Location,,,,,,,,,,,,
Adelaide,1.703226,0.634483,1.735484,0.320000,2.838710,3.173333,3.612903,1.896774,4.373333,2.612903,1.106667,2.800000
Albany,2.380645,0.748276,1.144828,3.153333,3.158065,4.010000,3.954839,3.777419,3.426667,2.025806,0.753333,0.650000
Albury,2.206452,1.013793,0.961290,0.546667,3.477419,2.866667,3.767742,2.400000,4.740000,1.980645,1.653333,0.735484
AliceSprings,1.290323,0.910345,0.522581,0.000000,1.832258,0.933333,0.000000,0.658065,1.640000,0.109677,0.233333,4.352000
BadgerysCreek,5.012903,0.441379,1.019355,0.346667,0.380645,8.346667,1.438710,1.890323,1.826667,0.458065,0.337931,0.728571
Ballarat,1.358621,0.355556,1.180645,0.460000,2.303226,2.353333,3.012903,2.051613,5.940000,3.303226,1.133333,0.890323
Bendigo,1.117241,0.162963,1.077419,0.493333,2.677419,1.913333,2.961290,2.612903,5.113333,1.883871,1.253333,0.941935
Brisbane,0.972414,0.523077,3.787097,0.426667,0.890323,8.826667,0.909677,1.019355,1.726667,0.974194,0.933333,3.290323
Cairns,9.316129,4.689655,8.329032,4.593103,9.336842,2.220000,2.741935,1.348387,4.500000,2.427273,0.765217,4.033333
Canberra,3.432258,0.806897,0.916129,0.226667,1.535484,4.806667,2.290323,1.490323,4.973333,1.406452,1.893333,2.083871
Cobar,0.728571,0.062069,2.344828,1.313333,2.438710,3.586667,1.058065,1.948387,3.406667,0.658065,1.126316,0.993548
CoffsHarbour,3.129032,1.086207,2.345161,3.876667,0.112903,11.350000,0.732258,5.706452,1.163333,0.841935,3.546667,2.051613
Dartmoor,0.606897,1.420690,0.922581,1.133333,3.238710,5.053333,4.116129,2.780645,3.640000,2.341935,1.560000,1.670968
Darwin,5.477419,5.186207,3.735484,1.546667,2.012903,0.000000,0.000000,0.000000,2.146667,4.219355,6.940000,13.122581
GoldCoast,3.360000,2.336000,1.745455,3.764286,0.600000,10.042857,0.607407,2.407407,1.284615,1.264000,0.992308,1.825806
Hobart,1.296774,0.751724,0.548387,0.293333,3.096774,3.846667,2.554839,0.509677,3.140000,2.690323,2.173333,1.825806
Katherine,8.112903,3.889655,3.245161,0.626667,1.438710,0.000000,0.179310,0.000000,1.933333,0.141935,1.350000,3.469565
Launceston,4.961290,0.848276,1.596774,0.920000,4.312903,4.483333,4.545161,2.083871,2.706667,2.377419,1.840000,2.287097
Melbourne,NaN,NaN,NaN,NaN,1.838710,1.813333,2.070968,1.974194,2.906667,2.045161,1.046667,1.277419
MelbourneAirport,1.445161,0.151724,0.877419,1.213333,1.516129,2.213333,2.045161,0.987097,3.326667,2.496774,1.326667,2.496774
Mildura,2.200000,0.006897,0.012903,0.100000,1.400000,0.606667,0.619355,0.993548,3.120000,0.800000,1.706667,0.180645
Moree,3.270588,0.110345,0.347826,0.453333,1.122581,2.106667,0.470968,1.612903,4.620000,1.832258,0.773333,1.135484
MountGambier,0.425806,1.668966,0.916129,1.046667,3.438710,5.433333,4.948387,2.779310,3.921429,2.290323,1.653333,1.917241
MountGinini,4.690323,1.427586,1.767742,0.520000,3.432258,9.153333,6.354839,2.277419,7.110345,3.600000,1.926667,2.967742
Newcastle,13.851613,2.475000,2.280645,2.140000,0.458065,6.713333,1.787097,1.674194,1.866667,1.813793,1.693333,1.768000
Nhil,1.193548,0.496296,1.116129,0.220000,1.322581,1.446667,1.993548,1.083871,3.113333,1.903226,0.453333,1.032258
NorahHead,7.013793,0.600000,4.980645,1.813333,0.412903,6.506667,2.664516,2.432258,2.306667,1.941935,1.173333,2.238710
NorfolkIsland,4.419355,9.165517,8.841379,2.740000,3.880645,3.920000,2.161290,3.516129,2.440000,1.290323,7.084211,0.375000
Nuriootpa,0.967742,0.424138,1.470968,0.483333,2.862069,3.140000,2.437931,2.054839,6.036667,1.512903,0.783333,1.658065
PearceRAAF,0.696552,0.034483,3.283871,2.273333,2.909677,3.140000,3.845161,4.329032,1.664286,1.307143,0.246667,0.445161
Penrith,9.929032,0.072000,0.541935,0.406667,0.268966,6.980000,1.776000,1.574194,1.666667,0.400000,0.585714,2.248276
Perth,0.490323,0.020690,0.541935,2.273333,3.612903,3.646667,4.503226,3.974194,2.293333,1.206452,0.480000,0.329032
PerthAirport,0.754839,0.027586,0.690323,2.053333,3.419355,2.880000,4.174194,4.245161,2.060000,1.219355,0.186667,0.277419
Portland,0.944828,2.806897,0.961290,1.386667,4.658065,4.000000,5.425806,3.522581,5.471429,3.703226,2.246667,1.524138
Richmond,8.593548,0.525926,0.441379,0.286667,0.135484,6.306667,1.845161,1.987097,1.846667,0.438710,1.353333,2.529032
Sale,3.613793,0.213793,1.954839,0.866667,1.219355,2.433333,3.303226,0.845161,1.207143,2.259259,1.780000,0.761290
SalmonGums,1.331034,0.496552,1.670968,1.093333,1.148387,1.906667,1.051613,1.729032,0.900000,0.374194,0.113333,0.593103
Sydney,8.058065,0.889655,6.232258,5.166667,0.232258,10.166667,3.374194,4.883871,2.333333,1.012903,0.906667,2.096774
SydneyAirport,8.477419,1.393103,5.025806,2.700000,0.432258,9.313333,3.683871,4.238710,2.260000,1.103226,0.893333,1.883871
Townsville,2.470968,3.262069,18.000000,0.700000,0.012903,1.966667,1.716129,0.677419,0.242857,0.264516,0.366667,1.064286
Tuggeranong,3.234483,1.162963,1.875862,0.235714,1.200000,6.133333,2.077419,1.232258,5.033333,1.392593,1.780000,3.012903
Uluru,0.081481,0.491667,0.935484,0.006667,2.406452,2.681481,0.690323,0.935484,0.520000,0.064516,0.046667,6.929032
WaggaWagga,1.780645,0.558621,1.077419,0.360000,3.813793,2.820000,2.987097,1.896774,5.700000,2.064516,1.041667,0.600000
Walpole,3.584000,1.427586,1.151724,4.221429,4.870968,5.408333,6.379310,6.448276,5.092857,2.928571,0.938462,1.703226
Watsonia,1.207407,0.324138,0.890323,1.700000,1.722581,2.393333,2.051613,1.780645,2.792857,3.048276,2.033333,3.800000
Williamtown,13.625806,1.117241,1.474074,5.585185,0.361290,5.230000,1.696774,1.800000,1.660000,2.406452,1.561538,11.680000
Witchcliffe,0.296296,0.324138,0.551724,1.735714,6.238710,7.650000,7.806452,7.348387,4.364286,2.751724,0.570370,0.832258
Wollongong,5.735484,1.710345,6.587097,1.820000,0.316129,14.553333,3.483871,3.612903,1.580000,0.200000,0.986207,1.586667
Woomera,0.012903,0.524138,0.774194,0.033333,0.945161,1.890000,0.222581,0.890323,1.500000,0.335484,0.016667,0.505000

In [ ]:
data_2016.pivot_table(index = 'Location', columns = 'Month', values = 'Sunshine', aggfunc = 'mean')

Month,1,2,3,4,5,6,7,8,9,10,11,12
Location,,,,,,,,,,,,
Albany,5.588000,7.825000,4.450000,3.473333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AliceSprings,9.427273,11.638462,9.558621,10.212500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brisbane,8.870000,9.781481,8.558065,7.853333,8.332258,5.400000,6.864516,8.577419,7.690000,9.909677,10.293103,8.806452
Cairns,8.576667,9.020690,7.116667,6.980952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dartmoor,8.873333,7.813793,5.293548,5.304545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Darwin,8.045161,8.065517,7.490323,9.320000,9.416129,10.266667,10.329032,10.383871,8.633333,9.145161,8.433333,5.922581
Hobart,6.900000,8.186207,6.335484,6.420000,4.287097,3.630000,4.993548,6.574194,6.043333,7.587097,7.413333,8.430000
Melbourne,NaN,NaN,NaN,8.400000,5.219355,3.850000,3.861290,5.738710,4.893333,6.941935,6.960000,8.374194
MelbourneAirport,6.912903,8.472414,5.835484,6.373333,5.219355,3.850000,3.861290,5.738710,4.893333,6.941935,6.960000,8.374194
Mildura,8.990000,11.496429,9.067742,7.892857,6.057143,4.950000,4.966667,7.377419,7.000000,9.270000,9.709524,10.245833
Moree,9.623077,11.200000,10.270000,9.272727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MountGambier,9.000000,7.813793,5.293548,5.304545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NorfolkIsland,7.643333,4.710714,6.546429,6.538462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nuriootpa,10.167742,10.537931,7.593548,7.306667,4.831579,4.810000,4.393103,6.722222,5.353571,8.970968,10.072414,10.060714
PearceRAAF,9.330000,11.641379,9.003226,6.413333,6.590323,5.686667,6.141935,6.193548,7.862069,9.762069,11.940000,12.045161
Perth,9.412903,11.641379,9.003226,6.413333,6.590323,5.686667,6.141935,6.193548,7.940000,9.725806,11.940000,12.045161
PerthAirport,9.412903,11.641379,9.003226,6.413333,6.590323,5.686667,6.141935,6.193548,7.940000,9.725806,11.940000,12.045161
Portland,8.900000,7.813793,5.293548,5.304545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sydney,6.600000,9.572414,7.412903,7.246667,7.451613,5.631034,6.663333,6.830000,7.466667,9.106452,9.500000,7.425806
SydneyAirport,6.600000,9.572414,7.412903,7.246667,7.451613,5.631034,6.663333,6.830000,7.466667,9.106452,9.500000,7.425806
Townsville,9.480645,9.210345,6.912903,8.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WaggaWagga,8.151613,11.500000,9.145161,8.957692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Watsonia,6.924138,8.472414,5.835484,6.373333,5.219355,3.850000,3.861290,5.738710,4.879310,7.010000,6.960000,8.100000
Williamtown,7.226667,10.913333,8.181250,6.723077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Woomera,10.387097,11.710345,7.609677,8.957692,7.644828,NaN,NaN,NaN,NaN,NaN,0.000000,NaN

Check here for (https://pandas.pydata.org/pandas-docs/stable/index.html) is the link to the official documentation of Pandas. Be sure to visit it inorder to explore to availability of functions in the library.