<a href="https://colab.research.google.com/github/preethisedigar/data_analytics_projects/blob/main/cricket_Tournament.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Case Study - Cricket Tournament

A panel wants to select players for an upcoming league match based on their fitness. Players from all significant cricket clubs have participated in a practice match, and their data is collected. Let us now explore NumPy features using the player's data.
Example - 1

Heights of the players is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it ?

In [ ]:
import numpy as np
# Define list
heights = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

In [ ]:
heights_inches = np.array(heights)
heights_inches

array([74, 74, 72, ..., 75, 75, 73])

In [ ]:
len(heights_inches)

1015

In [ ]:
heights_inches.size

1015

In [ ]:
heights_inches.shape #    rows X columns

(1015,)

In [ ]:
heights_m = heights_inches* 0.0245
heights_m

array([1.813 , 1.813 , 1.764 , ..., 1.8375, 1.8375, 1.7885])

In [ ]:
print(np.sort(heights_m))

[1.6415 1.6415 1.666  ... 2.009  2.009  2.0335]

In [ ]:
print(min(heights_m))

1.6415

In [ ]:
print(max(heights_m))

2.0335

In [ ]:
print(sum(heights_m))

1832.4775000000093

In [ ]:
print(heights_m==20)

[False False False ... False False False]

In [ ]:
print(heights_m>=20.34)

[False False False ... False False False]

In [ ]:
weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [ ]:
weights_kgs = np.array(weights_lb) * 0.453592
weights_kgs

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [ ]:
print(len(weights_kgs))

1015

In [ ]:
weights_kgs.size

1015

In [ ]:
weights_kgs.shape

(1015,)

In [ ]:
print(np.sort(weights_kgs))

[ 68.0388    68.0388    68.0388   ... 122.46984  126.098576 131.54168 ]

In [ ]:
print(min(weights_kgs))
print(max(weights_kgs))

68.0388
131.54167999999999

In [ ]:
# BMI
bmi = weights_kgs / (heights_m ** 2)
bmi

NameError: name 'weights_kgs' is not defined

In [ ]:
bmi < 21

array([False, False, False, ..., False, False, False])

In [ ]:
bmi[bmi < 21]

array([20.95729801])

In [ ]:
bmi[-1]

27.651717332702667

In [ ]:
bmi[0:20]

array([24.83946761, 29.66936409, 30.611705  , 30.611705  , 26.65909158,
       27.93493749, 33.17273827, 29.98102771, 30.22163895, 26.98292494,
       26.65909158, 25.52466215, 25.52945282, 22.07952676, 28.56982244,
       28.53046605, 26.80089526, 24.85320598, 27.20120397, 27.84882467])

In [ ]:
bmi[bmi>27]

array([29.66936409, 30.611705  , 30.611705  , 27.93493749, 33.17273827,
       29.98102771, 30.22163895, 28.56982244, 28.53046605, 27.20120397,
       27.84882467, 31.73931972, 28.7817866 , 30.22687214, 28.36073573,
       32.91370522, 32.24199695, 29.66936409, 29.36342861, 27.46141141,
       28.36073573, 30.48779091, 28.28939366, 28.42739071, 28.68468478,
       27.40476448, 28.03977007, 28.97937887, 30.0726534 , 28.36073573,
       27.73587644, 29.30583171, 28.28939366, 30.3593493 , 29.94584193,
       28.31906167, 36.27224656, 28.21174733, 30.3593493 , 29.88285488,
       28.21174733, 31.1968093 , 29.92057619, 28.36073573, 27.75937237,
       29.30155972, 30.09080935, 27.73245063, 30.22687214, 30.22687214,
       29.55516387, 28.28939366, 29.18850654, 37.47628464, 29.77877251,
       27.59940845, 29.82384717, 27.65171733, 30.3593493 , 30.3593493 ,
       31.1968093 , 31.73931972, 31.1968093 , 28.56982244, 28.21174733,
       28.8834556 , 28.36073573, 31.04901507, 32.42930493, 29.95157258,
       28.97937887, 28.29467707, 28.21174733, 30.09080935, 27.50991365,
       32.24199695, 29.68121743, 28.36073573, 27.47421723, 28.78251329,
       29.77877251, 31.04933451, 27.75937237, 27.59940845, 29.73708486,
       29.11737592, 28.48197632, 28.97937887, 35.11373546, 30.3593493 ,
       27.32541038, 28.78251329, 29.88285488, 27.59940845, 32.70740146,
       31.04933451, 28.8834556 , 28.8834556 , 28.42515464, 27.59940845,
       28.27938462, 30.3593493 , 27.75937237, 29.2115578 , 29.88285488,
       29.98102771, 31.90582769, 29.29977479, 30.22687214, 32.15331085,
       30.22687214, 28.03977007, 31.00661659, 28.8834556 , 30.74495738,
       27.69630452, 28.48197632, 28.28939366, 28.48197632, 29.88285488,
       28.42739071, 29.55516387, 29.49516515, 28.21174733, 30.75747502,
       31.73931972, 28.53046605, 30.71629358, 28.67703757, 28.21174733,
       28.56747449, 28.12836526, 28.07712837, 30.36121379, 37.3469798 ,
       29.31430507, 31.39910541, 27.58254549, 29.42082221, 34.60122939,
       28.48197632, 29.43666132, 32.06940524, 29.30155972, 28.71669469,
       28.92795044, 29.23150202, 31.1968093 , 31.34055512, 28.28939366,
       29.88285488, 28.97937887, 29.66936409, 27.54003906, 29.92057619,
       27.69630452, 31.18026882, 27.59940845, 31.16726371, 30.89858041,
       28.21174733, 27.32541038, 27.87540254, 27.73587644, 27.94644243,
       29.30155972, 29.15400476, 27.98347147, 30.3593493 , 28.93169174,
       29.30155972, 32.97913048, 27.59940845, 28.48197632, 27.73245063,
       27.59940845, 27.30005255, 28.78251329, 30.22687214, 31.05500562,
       27.93532469, 27.65171733, 30.611705  , 28.03977007, 29.95157258,
       28.56747449, 28.36073573, 29.30155972, 29.15400476, 28.36073573,
       30.22135225, 28.36073573, 30.3593493 , 27.54003906, 30.48779091,
       28.28939366, 27.99753565, 28.36073573, 31.61484076, 29.55516387,
       28.48197632, 31.34055512, 29.18850654, 28.36073573, 29.98102771,
       28.21174733, 30.58884008, 28.21174733, 32.06940524, 28.97937887,
       29.06975412, 27.59940845, 28.33769263, 30.48779091, 27.87540254,
       27.59940845, 27.54003906, 30.48779091, 27.59940845, 30.611705  ,
       30.3593493 , 28.64434308, 29.55516387, 28.36073573, 33.38133545,
       30.0286249 , 32.06940524, 29.23150202, 31.73931972, 30.22135225,
       30.74495738, 29.15400476, 32.29130789, 29.55516387, 27.69802961,
       27.59940845, 28.97937887, 27.59940845, 29.30155972, 31.32532859,
       29.23150202, 30.58884008, 28.97937887, 27.75937237, 31.90582769,
       28.93169174, 30.09080935, 28.56747449, 29.55516387, 28.36073573,
       30.92739629, 32.91370522, 32.70740146, 29.55516387, 28.71669469,
       29.98102771, 28.78251329, 29.77877251, 29.82915013, 28.48197632,
       28.56982244, 28.36073573, 27.93493749, 30.63534338, 29.11737592,
       28.42515464, 29.98102771, 30.0286249 , 31.39910541, 34.01569752,
       28.91334289, 27.54003906, 29.98102771, 30.13093285, 29.06975412,
       32.91370522, 32.97913048, 28.21174733, 30.3593493 , 28.36073573,
       27.47421723, 28.78251329, 29.2115578 , 29.77877251, 29.55516387,
       30.0726534 , 28.28939366, 28.33769263, 31.48007909, 29.23150202,
       27.59940845, 28.28939366, 27.2263063 , 34.03288287, 29.88285488,
       31.86337508, 28.78251329, 33.57875103, 28.21174733, 27.65171733,
       31.22610758, 30.48779091, 27.77621626, 30.0726534 , 31.73931972,
       30.09080935, 29.06975412, 30.48779091, 30.3593493 , 29.77877251,
       32.50064258, 29.31430507, 27.59940845, 28.28939366, 29.77877251,
       28.67703757, 29.66936409, 28.03977007, 27.54003906, 29.55516387,
       29.53131229, 31.04933451, 28.83890352, 29.66505237, 27.59940845,
       27.40476448, 31.90582769, 29.15400476, 28.97937887, 33.80927535,
       27.86670605, 31.46332564, 32.38593443, 35.45091966, 27.08450262,
       31.34055512, 33.23071989, 32.89845344, 31.34055512, 30.3593493 ,
       29.98102771, 28.97937887, 27.59940845, 28.03977007, 28.36073573,
       30.09253048, 30.3593493 , 29.05964314, 31.2682758 , 27.47421723,
       27.32541038, 32.06940524, 33.52710548, 31.1968093 , 30.89858041,
       29.6099972 , 28.21174733, 28.28939366, 29.77877251, 27.73245063,
       29.23150202, 29.44554481, 29.06975412, 27.65171733, 31.74424715,
       29.8095386 , 27.73245063, 31.1968093 , 27.54003906, 27.75937237,
       27.73740549, 27.94306402, 29.05964314, 29.31430507, 27.65171733,
       28.8834556 , 30.48779091, 30.48779091, 28.78251329, 28.03977007,
       30.89858041, 30.0726534 , 28.48197632, 29.23150202, 28.07740567,
       28.15139662, 28.53046605, 27.54003906, 28.21174733, 30.74495738,
       28.97937887, 28.56982244, 28.71669469, 29.59131483, 27.54003906,
       29.51842982, 28.78251329, 28.48197632, 28.78251329, 27.40250257,
       29.2115578 , 28.12836526, 28.53046605, 31.57028868, 30.89858041,
       30.0726534 , 28.48197632, 29.15400476, 28.36073573, 29.14734099,
       27.75937237, 29.55516387, 27.25899445, 34.03288287, 28.97937887,
       30.3593493 , 30.22135225, 27.69630452, 31.34055512, 31.48007909,
       29.15400476, 27.69630452, 28.53046605, 28.03977007, 28.42515464,
       29.23150202, 27.47421723, 28.48197632, 27.75937237, 31.1968093 ,
       27.11322443, 27.73245063, 28.48197632, 27.69630452, 28.97937887,
       33.11929014, 30.3593493 , 30.611705  , 28.21174733, 28.42515464,
       29.88285488, 29.15400476, 33.80927535, 28.36073573, 29.82384717,
       30.48779091, 31.39910541, 28.03977007, 27.69630452, 30.28083799,
       33.12903562, 27.69630452, 29.77877251, 29.98102771, 27.73245063,
       30.09080935, 29.49516515, 34.15558108, 27.59940845, 29.15400476,
       32.70740146, 35.56788581, 28.64434308, 31.39910541, 29.15400476,
       31.34055512, 27.47421723, 28.12836526, 29.15213891, 30.53530961,
       29.98102771, 30.3593493 , 28.36073573, 30.09080935, 30.22163895,
       28.7817866 , 27.2917801 , 28.48197632, 27.40250257, 29.88285488,
       29.17500211, 31.39910541, 31.73931972, 29.17500211, 27.04742028,
       31.86337508, 29.30155972, 27.69630452, 28.67703757, 29.55516387,
       31.33017396, 30.611705  , 27.14249743, 37.90020619, 28.42515464,
       28.42515464, 28.42515464, 29.42082221, 32.79825536, 30.06237987,
       27.87540254, 28.07740567, 29.15400476, 30.6298971 , 28.21174733,
       29.25537296, 30.91320194, 30.3593493 , 28.48197632, 32.42930493,
       28.21174733, 27.47421723, 30.74495738, 28.8834556 , 29.01779725,
       30.3593493 , 29.41628993, 31.48007909, 33.92812179, 32.75664976,
       30.611705  , 27.59940845, 31.61484076, 28.48197632, 28.09606646,
       27.94306402, 29.95157258, 31.34055512, 33.67127831, 32.06940524,
       28.56747449, 28.36073573, 27.79352101, 30.09080935, 30.09253048,
       29.88285488, 28.21174733, 28.36073573, 33.6232087 , 29.55516387,
       29.15400476, 28.8834556 , 31.57028868, 28.21174733, 30.89858041,
       28.52005645, 33.04804687, 27.47421723, 28.86246471, 30.611705  ,
       28.8834556 , 29.15400476, 31.22610758, 28.36073573, 27.98784457,
       29.6099972 , 27.59940845, 27.98784457, 28.28939366, 27.69630452,
       27.88235577, 29.53131229, 28.65168368, 27.59940845, 28.78251329,
       28.56538775, 31.04933451, 28.56538775, 28.48043064, 30.22687214,
       28.48197632, 28.97937887, 29.31430507, 31.48007909, 27.59940845,
       31.97331364, 29.82411908, 29.0441725 , 27.59940845, 32.97913048,
       32.50671531, 28.21174733, 30.48779091, 32.03107125, 27.77621626,
       29.06975412, 28.21174733, 27.75937237, 27.75937237, 27.18541733,
       29.55516387, 31.46332564, 28.92795044, 29.01779725, 28.03977007,
       29.49516515, 28.97937887, 28.12836526, 30.48779091, 29.95997974,
       29.8095386 , 27.80872237, 29.06975412, 27.69630452, 30.32016495,
       33.72865617, 30.22687214, 30.3009411 , 27.77586268, 31.39910541,
       30.3593493 , 30.06237987, 28.8834556 , 29.88285488, 29.66936409,
       28.56747449, 27.60504684, 30.89858041, 30.15703479, 29.55516387,
       27.54003906, 27.54003906, 27.65171733])

In [ ]:
len(bmi[bmi>27])

623

In [ ]:
bmi[bmi>27].shape

(623,)

In [ ]:
bmi[bmi>27].size

623

In [ ]:
under_weight = bmi[bmi < 23]
under_weight

array([22.07952676, 22.07952676, 22.241033  , 22.241033  , 21.86550357,
       22.68858858, 21.86550357, 22.68858858, 22.68858858, 22.241033  ,
       22.76951197, 21.66709505, 22.83808117, 22.89518102, 20.95729801,
       22.241033  , 22.83808117, 22.48577078, 22.76951197])

In [ ]:
max(bmi)

37.90020618980774

In [ ]:
bmi.max()

37.90020618980774

In [ ]:
min(bmi)

20.957298014716088

In [ ]:
bmi.min()

20.957298014716088

In [ ]:
# list of height and weight of the players.
  #            0           1
  #                      0   1
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180), (70, 185), (73, 189), (75, 185), (78, 219), (79, 230), (76, 205), (74, 230), (76, 195), (72, 180), (71, 192), (75, 225), (77, 203), (74, 195), (73, 182), (74, 188), (78, 200), (73, 180), (75, 200), (73, 200), (75, 245), (75, 240), (74, 215), (69, 185), (71, 175), (74, 199), (73, 200), (73, 215), (76, 200), (74, 205), (74, 206), (70, 186), (72, 188), (77, 220), (74, 210), (70, 195), (73, 200), (75, 200), (76, 212), (76, 224), (78, 210), (74, 205), (74, 220), (76, 195), (77, 200), (81, 260), (78, 228), (75, 270), (77, 200), (75, 210), (76, 190), (74, 220), (72, 180), (72, 205), (75, 210), (73, 220), (73, 211), (73, 200), (70, 180), (70, 190), (70, 170), (76, 230), (68, 155), (71, 185), (72, 185), (75, 200), (75, 225), (75, 225), (75, 220), (68, 160), (74, 205), (78, 235), (71, 250), (73, 210), (76, 190), (74, 160), (74, 200), (79, 205), (75, 222), (73, 195), (76, 205), (74, 220), (74, 220), (73, 170), (72, 185), (74, 195), (73, 220), (74, 230), (72, 180), (73, 220), (69, 180), (72, 180), (73, 170), (75, 210), (75, 215), (73, 200), (72, 213), (72, 180), (76, 192), (74, 235), (72, 185), (77, 235), (74, 210), (77, 222), (75, 210), (76, 230), (80, 220), (74, 180), (74, 190), (75, 200), (78, 210), (73, 194), (73, 180), (74, 190), (75, 240), (76, 200), (71, 198), (73, 200), (74, 195), (76, 210), (76, 220), (74, 190), (73, 210), (74, 225), (70, 180), (72, 185), (73, 170), (73, 185), (73, 185), (73, 180), (71, 178), (74, 175), (74, 200), (72, 204), (74, 211), (71, 190), (74, 210), (73, 190), (75, 190), (75, 185), (79, 290), (73, 175), (75, 185), (76, 200), (74, 220), (76, 170), (78, 220), (74, 190), (76, 220), (72, 205), (74, 200), (76, 250), (74, 225), (75, 215), (78, 210), (75, 215), (72, 195), (74, 200), (72, 194), (74, 220), (70, 180), (71, 180), (70, 170), (75, 195), (71, 180), (71, 170), (73, 206), (72, 205), (71, 200), (73, 225), (72, 201), (75, 225), (74, 233), (74, 180), (75, 225), (73, 180), (77, 220), (73, 180), (76, 237), (75, 215), (74, 190), (76, 235), (75, 190), (73, 180), (71, 165), (76, 195), (75, 200), (72, 190), (71, 190), (77, 185), (73, 185), (74, 205), (71, 190), (72, 205), (74, 206), (75, 220), (73, 208), (72, 170), (75, 195), (75, 210), (74, 190), (72, 211), (74, 230), (71, 170), (70, 185), (74, 185), (77, 241), (77, 225), (75, 210), (75, 175), (78, 230), (75, 200), (76, 215), (73, 198), (75, 226), (75, 278), (79, 215), (77, 230), (76, 240), (71, 184), (75, 219), (74, 170), (69, 218), (71, 190), (76, 225), (72, 220), (72, 176), (70, 190), (72, 197), (73, 204), (71, 167), (72, 180), (71, 195), (73, 220), (72, 215), (73, 185), (74, 190), (74, 205), (72, 205), (75, 200), (74, 210), (74, 215), (77, 200), (75, 205), (73, 211), (72, 190), (71, 208), (74, 200), (77, 210), (75, 232), (75, 230), (75, 210), (78, 220), (78, 210), (74, 202), (76, 212), (78, 225), (76, 170), (70, 190), (72, 200), (80, 237), (74, 220), (74, 170), (71, 193), (70, 190), (72, 150), (71, 220), (74, 200), (71, 190), (72, 185), (71, 185), (74, 200), (69, 172), (76, 220), (75, 225), (75, 190), (76, 195), (73, 219), (76, 190), (73, 197), (77, 200), (73, 195), (72, 210), (72, 177), (77, 220), (77, 235), (71, 180), (74, 195), (74, 195), (73, 190), (78, 230), (75, 190), (73, 200), (70, 190), (74, 190), (72, 200), (73, 200), (73, 184), (75, 200), (75, 180), (74, 219), (76, 187), (73, 200), (74, 220), (75, 205), (75, 190), (72, 170), (73, 160), (73, 215), (72, 175), (74, 205), (78, 200), (76, 214), (73, 200), (74, 190), (75, 180), (70, 205), (75, 220), (71, 190), (72, 215), (78, 235), (75, 191), (73, 200), (73, 181), (71, 200), (75, 210), (77, 240), (72, 185), (69, 165), (73, 190), (74, 185), (72, 175), (70, 155), (75, 210), (70, 170), (72, 175), (72, 220), (74, 210), (73, 205), (74, 200), (76, 205), (75, 195), (80, 240), (72, 150), (75, 200), (73, 215), (74, 202), (74, 200), (73, 190), (75, 205), (75, 190), (71, 160), (73, 215), (75, 185), (74, 200), (74, 190), (72, 210), (74, 185), (74, 220), (74, 190), (73, 202), (76, 205), (75, 220), (72, 175), (73, 160), (73, 190), (73, 200), (72, 229), (72, 206), (72, 220), (72, 180), (71, 195), (75, 175), (75, 188), (74, 230), (73, 190), (75, 200), (79, 190), (74, 219), (76, 235), (73, 180), (74, 180), (74, 180), (72, 200), (74, 234), (74, 185), (75, 220), (78, 223), (74, 200), (74, 210), (74, 200), (77, 210), (70, 190), (73, 177), (74, 227), (73, 180), (71, 195), (75, 199), (71, 175), (72, 185), (77, 240), (74, 210), (70, 180), (77, 194), (73, 225), (72, 180), (76, 205), (71, 193), (76, 230), (78, 230), (75, 220), (73, 200), (78, 249), (74, 190), (79, 208), (75, 245), (76, 250), (72, 160), (75, 192), (75, 220), (70, 170), (72, 197), (70, 155), (74, 190), (71, 200), (76, 220), (73, 210), (76, 228), (71, 190), (69, 160), (72, 184), (72, 180), (69, 180), (73, 200), (69, 176), (73, 160), (74, 222), (74, 211), (72, 195), (71, 200), (72, 175), (72, 206), (76, 240), (76, 185), (76, 260), (74, 185), (76, 221), (75, 205), (71, 200), (72, 170), (71, 201), (73, 205), (75, 185), (76, 205), (75, 245), (71, 220), (75, 210), (74, 220), (72, 185), (73, 175), (73, 170), (73, 180), (73, 200), (76, 210), (72, 175), (76, 220), (73, 206), (73, 180), (73, 210), (75, 195), (75, 200), (77, 200), (73, 164), (72, 180), (75, 220), (70, 195), (74, 205), (72, 170), (80, 240), (71, 210), (71, 195), (74, 200), (74, 205), (73, 192), (75, 190), (76, 170), (73, 240), (77, 200), (72, 205), (73, 175), (77, 250), (76, 220), (71, 224), (75, 210), (73, 195), (74, 180), (77, 245), (71, 175), (72, 180), (73, 215), (69, 175), (73, 180), (70, 195), (74, 230), (76, 230), (73, 205), (73, 215), (75, 195), (73, 180), (79, 205), (74, 180), (73, 190), (74, 180), (77, 190), (75, 190), (74, 220), (73, 210), (77, 255), (73, 190), (77, 230), (74, 200), (74, 205), (73, 210), (77, 225), (74, 215), (77, 220), (75, 205), (77, 200), (75, 220), (71, 197), (74, 225), (70, 187), (79, 245), (72, 185), (72, 185), (70, 175), (74, 200), (74, 180), (72, 188), (73, 225), (72, 200), (74, 210), (74, 245), (76, 213), (82, 231), (74, 165), (74, 228), (70, 210), (73, 250), (73, 191), (74, 190), (77, 200), (72, 215), (76, 254), (73, 232), (73, 180), (72, 215), (74, 220), (74, 180), (71, 200), (72, 170), (75, 195), (74, 210), (74, 200), (77, 220), (70, 165), (71, 180), (73, 200), (76, 200), (71, 170), (75, 224), (74, 220), (72, 180), (76, 198), (79, 240), (76, 239), (73, 185), (76, 210), (78, 220), (75, 200), (76, 195), (72, 220), (72, 230), (73, 170), (73, 220), (75, 230), (71, 165), (76, 205), (70, 192), (75, 210), (74, 205), (75, 200), (73, 210), (71, 185), (71, 195), (72, 202), (73, 205), (73, 195), (72, 180), (69, 200), (73, 185), (78, 240), (71, 185), (73, 220), (75, 205), (76, 205), (70, 180), (74, 201), (77, 190), (75, 208), (79, 240), (72, 180), (77, 230), (73, 195), (75, 215), (75, 190), (75, 195), (73, 215), (73, 215), (76, 220), (77, 220), (75, 230), (70, 195), (71, 190), (71, 195), (75, 209), (74, 204), (69, 170), (70, 185), (75, 205), (72, 175), (75, 210), (73, 190), (72, 180), (72, 180), (72, 160), (76, 235), (75, 200), (74, 210), (69, 180), (73, 190), (72, 197), (72, 203), (75, 205), (77, 170), (76, 200), (80, 250), (77, 200), (76, 220), (79, 200), (71, 190), (75, 170), (73, 190), (76, 220), (77, 215), (73, 206), (76, 215), (70, 185), (75, 235), (73, 188), (75, 230), (70, 195), (69, 168), (71, 190), (72, 160), (72, 200), (73, 200), (70, 189), (70, 180), (73, 190), (76, 200), (75, 220), (72, 187), (73, 240), (79, 190), (71, 180), (72, 185), (74, 210), (74, 220), (74, 219), (72, 190), (76, 193), (76, 175), (72, 180), (72, 215), (71, 210), (72, 200), (72, 190), (70, 185), (77, 220), (74, 170), (72, 195), (76, 205), (71, 195), (76, 210), (71, 190), (73, 190), (70, 180), (73, 220), (73, 190), (72, 186), (71, 185), (71, 190), (71, 180), (72, 190), (72, 170), (74, 210), (74, 240), (74, 220), (71, 180), (72, 210), (75, 210), (72, 195), (71, 160), (72, 180), (72, 205), (72, 200), (72, 185), (74, 245), (74, 190), (77, 210), (75, 200), (73, 200), (75, 222), (73, 215), (76, 240), (72, 170), (77, 220), (75, 156), (72, 190), (71, 202), (71, 221), (75, 200), (72, 190), (73, 210), (73, 190), (71, 200), (70, 165), (75, 190), (71, 185), (76, 230), (73, 208), (68, 209), (71, 175), (72, 180), (74, 200), (77, 205), (72, 200), (76, 250), (78, 210), (81, 230), (72, 244), (73, 202), (76, 240), (72, 200), (72, 215), (74, 177), (76, 210), (73, 170), (76, 215), (75, 217), (70, 198), (71, 200), (74, 220), (72, 170), (73, 200), (76, 230), (76, 231), (73, 183), (71, 192), (68, 167), (71, 190), (71, 180), (74, 180), (77, 215), (69, 160), (72, 205), (76, 223), (75, 175), (76, 170), (75, 190), (76, 240), (72, 175), (74, 230), (76, 223), (74, 196), (72, 167), (75, 195), (78, 190), (77, 250), (70, 190), (72, 190), (79, 190), (74, 170), (71, 160), (68, 150), (77, 225), (75, 220), (71, 209), (72, 210), (70, 176), (72, 260), (72, 195), (73, 190), (72, 184), (74, 180), (72, 195), (72, 195), (75, 219), (72, 225), (73, 212), (74, 202), (72, 185), (78, 200), (75, 209), (72, 200), (74, 195), (75, 228), (75, 210), (76, 190), (74, 212), (74, 190), (73, 218), (74, 220), (71, 190), (74, 235), (75, 210), (76, 200), (74, 188), (76, 210), (76, 235), (73, 188), (75, 215), (75, 216), (74, 220), (68, 180), (72, 185), (75, 200), (71, 210), (70, 220), (72, 185), (73, 231), (72, 210), (75, 195), (74, 200), (70, 205), (76, 200), (71, 190), (82, 250), (72, 185), (73, 180), (74, 170), (71, 180), (75, 208), (77, 235), (72, 215), (74, 244), (72, 220), (73, 185), (78, 230), (77, 190), (73, 200), (73, 180), (73, 190), (73, 196), (73, 180), (76, 230), (75, 224), (70, 160), (73, 178), (72, 205), (73, 185), (75, 210), (74, 180), (73, 190), (73, 200), (76, 257), (73, 190), (75, 220), (70, 165), (77, 205), (72, 200), (77, 208), (74, 185), (75, 215), (75, 170), (75, 235), (75, 210), (72, 170), (74, 180), (71, 170), (76, 190), (71, 150), (75, 230), (76, 203), (83, 260), (75, 246), (74, 186), (76, 210), (72, 198), (72, 210), (75, 215), (75, 180), (72, 200), (77, 245), (73, 200), (72, 192), (70, 192), (74, 200), (72, 192), (74, 205), (72, 190), (71, 186), (70, 170), (71, 197), (76, 219), (74, 200), (76, 220), (74, 207), (74, 225), (74, 207), (75, 212), (75, 225), (71, 170), (71, 190), (74, 210), (77, 230), (71, 210), (74, 200), (75, 238), (77, 234), (76, 222), (74, 200), (76, 190), (72, 170), (71, 220), (72, 223), (75, 210), (73, 215), (68, 196), (72, 175), (69, 175), (73, 189), (73, 205), (75, 210), (70, 180), (70, 180), (74, 197), (75, 220), (74, 228), (74, 190), (73, 204), (74, 165), (75, 216), (77, 220), (73, 208), (74, 210), (76, 215), (74, 195), (75, 200), (73, 215), (76, 229), (78, 240), (75, 207), (73, 205), (77, 208), (74, 185), (72, 190), (74, 170), (72, 208), (71, 225), (73, 190), (75, 225), (73, 185), (67, 180), (67, 165), (76, 240), (74, 220), (73, 212), (70, 163), (75, 215), (70, 175), (72, 205), (77, 210), (79, 205), (78, 208), (74, 215), (75, 180), (75, 200), (78, 230), (76, 211), (75, 230), (69, 190), (75, 220), (72, 180), (75, 205), (73, 190), (74, 180), (75, 205), (75, 190), (73, 195)]

In [ ]:
players[1][1]

215

In [ ]:
players[1][0]

74

In [ ]:
players[0][0]

74

In [ ]:
players[99][1] # 100th players weight

195

In [ ]:
players_array = np.array(players) * [0.0245, 0.453592]
players_array

array([[ 1.813  , 81.64656],
       [ 1.813  , 97.52228],
       [ 1.764  , 95.25432],
       ...,
       [ 1.8375 , 92.98636],
       [ 1.8375 , 86.18248],
       [ 1.7885 , 88.45044]])

In [ ]:
players_array.shape

(1015, 2)

In [ ]:
players_array.ndim # number of dimensions

2

In [ ]:
players_array.dtype # data type

dtype('float64')

In [ ]:
players_array.itemsize # number of bytes to store single element

8

In [ ]:
players_array[0]

array([ 1.813  , 81.64656])

In [ ]:
players_array[0][1]

81.64656

In [ ]:
players_array[99]

array([ 1.813  , 88.45044])

In [ ]:
players_array[99][1]

88.45044

In [ ]:
players_array[99][0]

1.8130000000000002

In [ ]:
# to fetch only the weights of players between 80 to 90
result = players_array[(players_array[:,1] > 80)]

In [ ]:
result

array([[ 1.813  , 81.64656],
       [ 1.813  , 97.52228],
       [ 1.764  , 95.25432],
       ...,
       [ 1.8375 , 92.98636],
       [ 1.8375 , 86.18248],
       [ 1.7885 , 88.45044]])

In [ ]:
result = players_array[(players_array[:,1] > 80) & (players_array[:,1] <= 90)]
result

array([[ 1.813   , 81.64656 ],
       [ 1.7885  , 85.275296],
       [ 1.7395  , 81.64656 ],
       [ 1.7885  , 85.275296],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 83.91452 ],
       [ 1.6905  , 81.64656 ],
       [ 1.715   , 83.91452 ],
       [ 1.7885  , 85.728888],
       [ 1.8375  , 83.91452 ],
       [ 1.862   , 88.45044 ],
       [ 1.764   , 81.64656 ],
       [ 1.7395  , 87.089664],
       [ 1.813   , 88.45044 ],
       [ 1.7885  , 82.553744],
       [ 1.813   , 85.275296],
       [ 1.7885  , 81.64656 ],
       [ 1.6905  , 83.91452 ],
       [ 1.715   , 84.368112],
       [ 1.764   , 85.275296],
       [ 1.715   , 88.45044 ],
       [ 1.862   , 88.45044 ],
       [ 1.862   , 86.18248 ],
       [ 1.764   , 81.64656 ],
       [ 1.715   , 81.64656 ],
       [ 1.715   , 86.18248 ],
       [ 1.7395  , 83.91452 ],
       [ 1.764   , 83.91452 ],
       [ 1.862   , 86.18248 ],
       [ 1.7885  , 88.45044 ],
       [ 1.764   , 83.91452 ],
       [ 1.813   , 88.45044 ],
       [ 1.764   , 81.64656 ],
       [ 1.6905  , 81.64656 ],
       [ 1.764   , 81.64656 ],
       [ 1.764   , 81.64656 ],
       [ 1.862   , 87.089664],
       [ 1.764   , 83.91452 ],
       [ 1.813   , 81.64656 ],
       [ 1.813   , 86.18248 ],
       [ 1.7885  , 87.996848],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 86.18248 ],
       [ 1.7395  , 89.811216],
       [ 1.813   , 88.45044 ],
       [ 1.813   , 86.18248 ],
       [ 1.715   , 81.64656 ],
       [ 1.764   , 83.91452 ],
       [ 1.7885  , 83.91452 ],
       [ 1.7885  , 83.91452 ],
       [ 1.7885  , 81.64656 ],
       [ 1.7395  , 80.739376],
       [ 1.7395  , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.8375  , 83.91452 ],
       [ 1.8375  , 83.91452 ],
       [ 1.813   , 86.18248 ],
       [ 1.764   , 88.45044 ],
       [ 1.764   , 87.996848],
       [ 1.715   , 81.64656 ],
       [ 1.7395  , 81.64656 ],
       [ 1.8375  , 88.45044 ],
       [ 1.7395  , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.7885  , 81.64656 ],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.7885  , 81.64656 ],
       [ 1.862   , 88.45044 ],
       [ 1.764   , 86.18248 ],
       [ 1.7395  , 86.18248 ],
       [ 1.8865  , 83.91452 ],
       [ 1.7885  , 83.91452 ],
       [ 1.7395  , 86.18248 ],
       [ 1.8375  , 88.45044 ],
       [ 1.813   , 86.18248 ],
       [ 1.715   , 83.91452 ],
       [ 1.813   , 83.91452 ],
       [ 1.7885  , 89.811216],
       [ 1.7395  , 83.460928],
       [ 1.7395  , 86.18248 ],
       [ 1.715   , 86.18248 ],
       [ 1.764   , 89.357624],
       [ 1.764   , 81.64656 ],
       [ 1.7395  , 88.45044 ],
       [ 1.7885  , 83.91452 ],
       [ 1.813   , 86.18248 ],
       [ 1.764   , 86.18248 ],
       [ 1.715   , 86.18248 ],
       [ 1.7395  , 87.543256],
       [ 1.715   , 86.18248 ],
       [ 1.7395  , 86.18248 ],
       [ 1.764   , 83.91452 ],
       [ 1.7395  , 83.91452 ],
       [ 1.8375  , 86.18248 ],
       [ 1.862   , 88.45044 ],
       [ 1.862   , 86.18248 ],
       [ 1.7885  , 89.357624],
       [ 1.7885  , 88.45044 ],
       [ 1.764   , 80.285784],
       [ 1.7395  , 81.64656 ],
       [ 1.813   , 88.45044 ],
       [ 1.813   , 88.45044 ],
       [ 1.7885  , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.715   , 86.18248 ],
       [ 1.813   , 86.18248 ],
       [ 1.7885  , 83.460928],
       [ 1.8375  , 81.64656 ],
       [ 1.862   , 84.821704],
       [ 1.8375  , 86.18248 ],
       [ 1.813   , 86.18248 ],
       [ 1.8375  , 81.64656 ],
       [ 1.7395  , 86.18248 ],
       [ 1.8375  , 86.636072],
       [ 1.7885  , 82.100152],
       [ 1.764   , 83.91452 ],
       [ 1.7885  , 86.18248 ],
       [ 1.813   , 83.91452 ],
       [ 1.8375  , 88.45044 ],
       [ 1.7885  , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.8375  , 83.91452 ],
       [ 1.813   , 86.18248 ],
       [ 1.813   , 83.91452 ],
       [ 1.813   , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 81.64656 ],
       [ 1.7395  , 88.45044 ],
       [ 1.8375  , 85.275296],
       [ 1.7885  , 86.18248 ],
       [ 1.9355  , 86.18248 ],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.813   , 83.91452 ],
       [ 1.715   , 86.18248 ],
       [ 1.7885  , 80.285784],
       [ 1.7885  , 81.64656 ],
       [ 1.7395  , 88.45044 ],
       [ 1.764   , 83.91452 ],
       [ 1.715   , 81.64656 ],
       [ 1.8865  , 87.996848],
       [ 1.764   , 81.64656 ],
       [ 1.7395  , 87.543256],
       [ 1.813   , 86.18248 ],
       [ 1.8375  , 87.089664],
       [ 1.764   , 89.357624],
       [ 1.813   , 86.18248 ],
       [ 1.7395  , 86.18248 ],
       [ 1.764   , 83.460928],
       [ 1.764   , 81.64656 ],
       [ 1.6905  , 81.64656 ],
       [ 1.764   , 88.45044 ],
       [ 1.862   , 83.91452 ],
       [ 1.813   , 83.91452 ],
       [ 1.8375  , 83.91452 ],
       [ 1.764   , 83.91452 ],
       [ 1.7885  , 81.64656 ],
       [ 1.7885  , 81.64656 ],
       [ 1.8375  , 88.45044 ],
       [ 1.764   , 81.64656 ],
       [ 1.715   , 88.45044 ],
       [ 1.7395  , 88.45044 ],
       [ 1.7885  , 87.089664],
       [ 1.8375  , 86.18248 ],
       [ 1.7885  , 88.45044 ],
       [ 1.813   , 81.64656 ],
       [ 1.764   , 81.64656 ],
       [ 1.7885  , 81.64656 ],
       [ 1.715   , 88.45044 ],
       [ 1.8375  , 88.45044 ],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.813   , 81.64656 ],
       [ 1.8865  , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.7395  , 89.357624],
       [ 1.715   , 84.821704],
       [ 1.764   , 83.91452 ],
       [ 1.764   , 83.91452 ],
       [ 1.813   , 81.64656 ],
       [ 1.764   , 85.275296],
       [ 1.7885  , 86.636072],
       [ 1.813   , 86.18248 ],
       [ 1.7885  , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.8375  , 88.45044 ],
       [ 1.7395  , 81.64656 ],
       [ 1.764   , 81.64656 ],
       [ 1.862   , 89.811216],
       [ 1.7885  , 83.91452 ],
       [ 1.862   , 88.45044 ],
       [ 1.715   , 87.089664],
       [ 1.7395  , 83.91452 ],
       [ 1.7395  , 88.45044 ],
       [ 1.7885  , 88.45044 ],
       [ 1.764   , 81.64656 ],
       [ 1.7885  , 83.91452 ],
       [ 1.7395  , 83.91452 ],
       [ 1.715   , 81.64656 ],
       [ 1.8865  , 86.18248 ],
       [ 1.764   , 81.64656 ],
       [ 1.7885  , 88.45044 ],
       [ 1.8375  , 86.18248 ],
       [ 1.8375  , 88.45044 ],
       [ 1.715   , 88.45044 ],
       [ 1.7395  , 86.18248 ],
       [ 1.7395  , 88.45044 ],
       [ 1.715   , 83.91452 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 81.64656 ],
       [ 1.764   , 81.64656 ],
       [ 1.6905  , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 89.357624],
       [ 1.7395  , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.715   , 83.91452 ],
       [ 1.7885  , 85.275296],
       [ 1.715   , 88.45044 ],
       [ 1.7395  , 86.18248 ],
       [ 1.715   , 85.728888],
       [ 1.715   , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 84.821704],
       [ 1.9355  , 86.18248 ],
       [ 1.7395  , 81.64656 ],
       [ 1.764   , 83.91452 ],
       [ 1.764   , 86.18248 ],
       [ 1.862   , 87.543256],
       [ 1.764   , 81.64656 ],
       [ 1.764   , 86.18248 ],
       [ 1.715   , 83.91452 ],
       [ 1.764   , 88.45044 ],
       [ 1.7395  , 88.45044 ],
       [ 1.7395  , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.715   , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 84.368112],
       [ 1.7395  , 83.91452 ],
       [ 1.7395  , 86.18248 ],
       [ 1.7395  , 81.64656 ],
       [ 1.764   , 86.18248 ],
       [ 1.7395  , 81.64656 ],
       [ 1.764   , 88.45044 ],
       [ 1.764   , 81.64656 ],
       [ 1.764   , 83.91452 ],
       [ 1.813   , 86.18248 ],
       [ 1.764   , 86.18248 ],
       [ 1.764   , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.8375  , 86.18248 ],
       [ 1.7395  , 83.91452 ],
       [ 1.764   , 81.64656 ],
       [ 1.813   , 80.285784],
       [ 1.715   , 89.811216],
       [ 1.7885  , 83.007336],
       [ 1.7395  , 87.089664],
       [ 1.7395  , 86.18248 ],
       [ 1.7395  , 81.64656 ],
       [ 1.813   , 81.64656 ],
       [ 1.8375  , 86.18248 ],
       [ 1.813   , 88.904032],
       [ 1.8375  , 88.45044 ],
       [ 1.911   , 86.18248 ],
       [ 1.715   , 86.18248 ],
       [ 1.764   , 86.18248 ],
       [ 1.9355  , 86.18248 ],
       [ 1.764   , 88.45044 ],
       [ 1.7885  , 86.18248 ],
       [ 1.764   , 83.460928],
       [ 1.813   , 81.64656 ],
       [ 1.764   , 88.45044 ],
       [ 1.764   , 88.45044 ],
       [ 1.764   , 83.91452 ],
       [ 1.813   , 88.45044 ],
       [ 1.862   , 86.18248 ],
       [ 1.813   , 86.18248 ],
       [ 1.7395  , 86.18248 ],
       [ 1.813   , 85.275296],
       [ 1.7885  , 85.275296],
       [ 1.666   , 81.64656 ],
       [ 1.764   , 83.91452 ],
       [ 1.764   , 83.91452 ],
       [ 1.8375  , 88.45044 ],
       [ 1.7395  , 86.18248 ],
       [ 1.764   , 83.91452 ],
       [ 1.7885  , 81.64656 ],
       [ 1.7395  , 81.64656 ],
       [ 1.7885  , 83.91452 ],
       [ 1.8865  , 86.18248 ],
       [ 1.7885  , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.7885  , 88.904032],
       [ 1.7885  , 81.64656 ],
       [ 1.7885  , 80.739376],
       [ 1.7885  , 83.91452 ],
       [ 1.813   , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.813   , 83.91452 ],
       [ 1.813   , 81.64656 ],
       [ 1.862   , 86.18248 ],
       [ 1.813   , 84.368112],
       [ 1.764   , 89.811216],
       [ 1.8375  , 81.64656 ],
       [ 1.764   , 87.089664],
       [ 1.715   , 87.089664],
       [ 1.764   , 87.089664],
       [ 1.764   , 86.18248 ],
       [ 1.7395  , 84.368112],
       [ 1.7395  , 89.357624],
       [ 1.7395  , 86.18248 ],
       [ 1.862   , 86.18248 ],
       [ 1.666   , 88.904032],
       [ 1.7885  , 85.728888],
       [ 1.715   , 81.64656 ],
       [ 1.715   , 81.64656 ],
       [ 1.813   , 89.357624],
       [ 1.813   , 86.18248 ],
       [ 1.813   , 88.45044 ],
       [ 1.813   , 83.91452 ],
       [ 1.764   , 86.18248 ],
       [ 1.7885  , 86.18248 ],
       [ 1.7885  , 83.91452 ],
       [ 1.6415  , 81.64656 ],
       [ 1.8375  , 81.64656 ],
       [ 1.6905  , 86.18248 ],
       [ 1.764   , 81.64656 ],
       [ 1.7885  , 86.18248 ],
       [ 1.813   , 81.64656 ],
       [ 1.8375  , 86.18248 ],
       [ 1.7885  , 88.45044 ]])

In [ ]:
len(result)

339

In [ ]:
result[:,1] # fetching only the weights

array([81.64656 , 85.275296, 81.64656 , 85.275296, 81.64656 , 83.91452 ,
       81.64656 , 83.91452 , 85.728888, 83.91452 , 88.45044 , 81.64656 ,
       87.089664, 88.45044 , 82.553744, 85.275296, 81.64656 , 83.91452 ,
       84.368112, 85.275296, 88.45044 , 88.45044 , 86.18248 , 81.64656 ,
       81.64656 , 86.18248 , 83.91452 , 83.91452 , 86.18248 , 88.45044 ,
       83.91452 , 88.45044 , 81.64656 , 81.64656 , 81.64656 , 81.64656 ,
       87.089664, 83.91452 , 81.64656 , 86.18248 , 87.996848, 81.64656 ,
       86.18248 , 89.811216, 88.45044 , 86.18248 , 81.64656 , 83.91452 ,
       83.91452 , 83.91452 , 81.64656 , 80.739376, 86.18248 , 86.18248 ,
       86.18248 , 83.91452 , 83.91452 , 86.18248 , 88.45044 , 87.996848,
       81.64656 , 81.64656 , 88.45044 , 81.64656 , 81.64656 , 81.64656 ,
       81.64656 , 86.18248 , 86.18248 , 81.64656 , 88.45044 , 86.18248 ,
       86.18248 , 83.91452 , 83.91452 , 86.18248 , 88.45044 , 86.18248 ,
       83.91452 , 83.91452 , 89.811216, 83.460928, 86.18248 , 86.18248 ,
       89.357624, 81.64656 , 88.45044 , 83.91452 , 86.18248 , 86.18248 ,
       86.18248 , 87.543256, 86.18248 , 86.18248 , 83.91452 , 83.91452 ,
       86.18248 , 88.45044 , 86.18248 , 89.357624, 88.45044 , 80.285784,
       81.64656 , 88.45044 , 88.45044 , 86.18248 , 86.18248 , 86.18248 ,
       86.18248 , 83.460928, 81.64656 , 84.821704, 86.18248 , 86.18248 ,
       81.64656 , 86.18248 , 86.636072, 82.100152, 83.91452 , 86.18248 ,
       83.91452 , 88.45044 , 86.18248 , 86.18248 , 83.91452 , 86.18248 ,
       83.91452 , 86.18248 , 86.18248 , 81.64656 , 88.45044 , 85.275296,
       86.18248 , 86.18248 , 81.64656 , 81.64656 , 81.64656 , 83.91452 ,
       86.18248 , 80.285784, 81.64656 , 88.45044 , 83.91452 , 81.64656 ,
       87.996848, 81.64656 , 87.543256, 86.18248 , 87.089664, 89.357624,
       86.18248 , 86.18248 , 83.460928, 81.64656 , 81.64656 , 88.45044 ,
       83.91452 , 83.91452 , 83.91452 , 83.91452 , 81.64656 , 81.64656 ,
       88.45044 , 81.64656 , 88.45044 , 88.45044 , 87.089664, 86.18248 ,
       88.45044 , 81.64656 , 81.64656 , 81.64656 , 88.45044 , 88.45044 ,
       81.64656 , 81.64656 , 86.18248 , 81.64656 , 86.18248 , 86.18248 ,
       86.18248 , 89.357624, 84.821704, 83.91452 , 83.91452 , 81.64656 ,
       85.275296, 86.636072, 86.18248 , 81.64656 , 81.64656 , 88.45044 ,
       81.64656 , 81.64656 , 89.811216, 83.91452 , 88.45044 , 87.089664,
       83.91452 , 88.45044 , 88.45044 , 81.64656 , 83.91452 , 83.91452 ,
       81.64656 , 86.18248 , 81.64656 , 88.45044 , 86.18248 , 88.45044 ,
       88.45044 , 86.18248 , 88.45044 , 83.91452 , 86.18248 , 81.64656 ,
       81.64656 , 81.64656 , 86.18248 , 89.357624, 86.18248 , 86.18248 ,
       83.91452 , 85.275296, 88.45044 , 86.18248 , 85.728888, 81.64656 ,
       86.18248 , 84.821704, 86.18248 , 81.64656 , 83.91452 , 86.18248 ,
       87.543256, 81.64656 , 86.18248 , 83.91452 , 88.45044 , 88.45044 ,
       86.18248 , 86.18248 , 81.64656 , 86.18248 , 84.368112, 83.91452 ,
       86.18248 , 81.64656 , 86.18248 , 81.64656 , 88.45044 , 81.64656 ,
       83.91452 , 86.18248 , 86.18248 , 86.18248 , 86.18248 , 86.18248 ,
       83.91452 , 81.64656 , 80.285784, 89.811216, 83.007336, 87.089664,
       86.18248 , 81.64656 , 81.64656 , 86.18248 , 88.904032, 88.45044 ,
       86.18248 , 86.18248 , 86.18248 , 86.18248 , 88.45044 , 86.18248 ,
       83.460928, 81.64656 , 88.45044 , 88.45044 , 83.91452 , 88.45044 ,
       86.18248 , 86.18248 , 86.18248 , 85.275296, 85.275296, 81.64656 ,
       83.91452 , 83.91452 , 88.45044 , 86.18248 , 83.91452 , 81.64656 ,
       81.64656 , 83.91452 , 86.18248 , 81.64656 , 86.18248 , 88.904032,
       81.64656 , 80.739376, 83.91452 , 81.64656 , 86.18248 , 86.18248 ,
       83.91452 , 81.64656 , 86.18248 , 84.368112, 89.811216, 81.64656 ,
       87.089664, 87.089664, 87.089664, 86.18248 , 84.368112, 89.357624,
       86.18248 , 86.18248 , 88.904032, 85.728888, 81.64656 , 81.64656 ,
       89.357624, 86.18248 , 88.45044 , 83.91452 , 86.18248 , 86.18248 ,
       83.91452 , 81.64656 , 81.64656 , 86.18248 , 81.64656 , 86.18248 ,
       81.64656 , 86.18248 , 88.45044 ])

In [ ]:
tall_players = players_array[players_array[:,0] > 1.8]
tall_players

array([[  1.813   ,  81.64656 ],
       [  1.813   ,  97.52228 ],
       [  1.862   , 104.779752],
       ...,
       [  1.813   ,  81.64656 ],
       [  1.8375  ,  92.98636 ],
       [  1.8375  ,  86.18248 ]])

In [ ]:
tall_players[:,0]

array([1.813 , 1.813 , 1.862 , 1.813 , 1.813 , 1.8375, 1.911 , 1.9355,
       1.862 , 1.813 , 1.862 , 1.8375, 1.8865, 1.813 , 1.813 , 1.911 ,
       1.8375, 1.8375, 1.8375, 1.813 , 1.813 , 1.862 , 1.813 , 1.813 ,
       1.8865, 1.813 , 1.8375, 1.862 , 1.862 , 1.911 , 1.813 , 1.813 ,
       1.862 , 1.8865, 1.9845, 1.911 , 1.8375, 1.8865, 1.8375, 1.862 ,
       1.813 , 1.8375, 1.862 , 1.8375, 1.8375, 1.8375, 1.8375, 1.813 ,
       1.911 , 1.862 , 1.813 , 1.813 , 1.9355, 1.8375, 1.862 , 1.813 ,
       1.813 , 1.813 , 1.813 , 1.8375, 1.8375, 1.862 , 1.813 , 1.8865,
       1.813 , 1.8865, 1.8375, 1.862 , 1.96  , 1.813 , 1.813 , 1.8375,
       1.911 , 1.813 , 1.8375, 1.862 , 1.813 , 1.862 , 1.862 , 1.813 ,
       1.813 , 1.813 , 1.813 , 1.813 , 1.813 , 1.8375, 1.8375, 1.9355,
       1.8375, 1.862 , 1.813 , 1.862 , 1.911 , 1.813 , 1.862 , 1.813 ,
       1.862 , 1.813 , 1.8375, 1.911 , 1.8375, 1.813 , 1.813 , 1.8375,
       1.8375, 1.813 , 1.813 , 1.8375, 1.8865, 1.862 , 1.8375, 1.813 ,
       1.862 , 1.8375, 1.862 , 1.8375, 1.8865, 1.813 , 1.813 , 1.8375,
       1.8375, 1.8375, 1.813 , 1.813 , 1.813 , 1.8865, 1.8865, 1.8375,
       1.8375, 1.911 , 1.8375, 1.862 , 1.8375, 1.8375, 1.9355, 1.8865,
       1.862 , 1.8375, 1.813 , 1.862 , 1.813 , 1.813 , 1.8375, 1.813 ,
       1.813 , 1.8865, 1.8375, 1.813 , 1.8865, 1.8375, 1.8375, 1.8375,
       1.911 , 1.911 , 1.813 , 1.862 , 1.911 , 1.862 , 1.96  , 1.813 ,
       1.813 , 1.813 , 1.813 , 1.862 , 1.8375, 1.8375, 1.862 , 1.862 ,
       1.8865, 1.8865, 1.8865, 1.813 , 1.813 , 1.911 , 1.8375, 1.813 ,
       1.8375, 1.8375, 1.813 , 1.862 , 1.813 , 1.8375, 1.8375, 1.813 ,
       1.911 , 1.862 , 1.813 , 1.8375, 1.8375, 1.911 , 1.8375, 1.8375,
       1.8865, 1.813 , 1.8375, 1.813 , 1.813 , 1.862 , 1.8375, 1.96  ,
       1.8375, 1.813 , 1.813 , 1.8375, 1.8375, 1.8375, 1.813 , 1.813 ,
       1.813 , 1.813 , 1.813 , 1.862 , 1.8375, 1.8375, 1.8375, 1.813 ,
       1.8375, 1.9355, 1.813 , 1.862 , 1.813 , 1.813 , 1.813 , 1.813 ,
       1.8375, 1.911 , 1.813 , 1.813 , 1.813 , 1.8865, 1.813 , 1.8375,
       1.8865, 1.813 , 1.8865, 1.862 , 1.862 , 1.911 , 1.8375, 1.911 ,
       1.813 , 1.9355, 1.8375, 1.862 , 1.8375, 1.8375, 1.813 , 1.862 ,
       1.862 , 1.813 , 1.813 , 1.862 , 1.862 , 1.862 , 1.813 , 1.862 ,
       1.8375, 1.8375, 1.862 , 1.8375, 1.8375, 1.813 , 1.862 , 1.862 ,
       1.8375, 1.8375, 1.8865, 1.8375, 1.813 , 1.96  , 1.813 , 1.813 ,
       1.8375, 1.862 , 1.8865, 1.8865, 1.862 , 1.8375, 1.813 , 1.8865,
       1.813 , 1.862 , 1.8375, 1.9355, 1.813 , 1.813 , 1.8865, 1.8375,
       1.813 , 1.8865, 1.8865, 1.813 , 1.813 , 1.8865, 1.813 , 1.8865,
       1.8375, 1.8865, 1.8375, 1.813 , 1.9355, 1.813 , 1.813 , 1.813 ,
       1.813 , 1.862 , 2.009 , 1.813 , 1.813 , 1.813 , 1.8865, 1.862 ,
       1.813 , 1.813 , 1.8375, 1.813 , 1.813 , 1.8865, 1.862 , 1.8375,
       1.813 , 1.862 , 1.9355, 1.862 , 1.862 , 1.911 , 1.8375, 1.862 ,
       1.8375, 1.862 , 1.8375, 1.813 , 1.8375, 1.911 , 1.8375, 1.862 ,
       1.813 , 1.8865, 1.8375, 1.9355, 1.8865, 1.8375, 1.8375, 1.8375,
       1.862 , 1.8865, 1.8375, 1.8375, 1.813 , 1.8375, 1.8375, 1.862 ,
       1.8375, 1.813 , 1.8375, 1.8865, 1.862 , 1.96  , 1.8865, 1.862 ,
       1.9355, 1.8375, 1.862 , 1.8865, 1.862 , 1.8375, 1.8375, 1.862 ,
       1.8375, 1.9355, 1.813 , 1.813 , 1.813 , 1.862 , 1.862 , 1.8865,
       1.813 , 1.862 , 1.862 , 1.813 , 1.813 , 1.813 , 1.8375, 1.813 ,
       1.813 , 1.8865, 1.8375, 1.8375, 1.862 , 1.8865, 1.8375, 1.8375,
       1.8375, 1.862 , 1.813 , 1.8865, 1.862 , 1.911 , 1.9845, 1.862 ,
       1.813 , 1.862 , 1.862 , 1.8375, 1.813 , 1.862 , 1.862 , 1.813 ,
       1.8865, 1.862 , 1.8375, 1.862 , 1.8375, 1.862 , 1.813 , 1.862 ,
       1.813 , 1.8375, 1.911 , 1.8865, 1.9355, 1.813 , 1.8865, 1.8375,
       1.813 , 1.8375, 1.813 , 1.911 , 1.8375, 1.813 , 1.8375, 1.8375,
       1.862 , 1.813 , 1.813 , 1.813 , 1.813 , 1.8375, 1.862 , 1.813 ,
       1.862 , 1.862 , 1.8375, 1.8375, 1.813 , 1.8375, 1.8375, 1.813 ,
       1.862 , 2.009 , 1.813 , 1.8375, 1.8865, 1.813 , 1.911 , 1.8865,
       1.862 , 1.8375, 1.8375, 1.813 , 1.862 , 1.8375, 1.8865, 1.8865,
       1.813 , 1.8375, 1.8375, 1.8375, 1.8375, 1.813 , 1.862 , 1.8375,
       1.862 , 2.0335, 1.8375, 1.813 , 1.862 , 1.8375, 1.8375, 1.8865,
       1.813 , 1.813 , 1.862 , 1.813 , 1.862 , 1.813 , 1.813 , 1.813 ,
       1.8375, 1.8375, 1.813 , 1.8865, 1.813 , 1.8375, 1.8865, 1.862 ,
       1.813 , 1.862 , 1.8375, 1.8375, 1.813 , 1.8375, 1.813 , 1.813 ,
       1.813 , 1.8375, 1.8865, 1.813 , 1.862 , 1.813 , 1.8375, 1.862 ,
       1.911 , 1.8375, 1.8865, 1.813 , 1.813 , 1.8375, 1.862 , 1.813 ,
       1.8375, 1.8865, 1.9355, 1.911 , 1.813 , 1.8375, 1.8375, 1.911 ,
       1.862 , 1.8375, 1.8375, 1.8375, 1.813 , 1.8375, 1.8375])

In [ ]:
len(tall_players)

535

In [ ]:
skills = np.array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper', 'Keeper', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman'])

In [ ]:
np.unique(skills) #fetching you the unique elements in the skills list

array(['Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman'], dtype='<U14')

In [ ]:
len(skills)

1015

In [ ]:
batsmen = players_array[skills == 'Batsman']
batsmen

array([[  1.813   ,  97.52228 ],
       [  1.7885  ,  85.275296],
       [  1.6905  ,  94.800728],
       [  1.7395  ,  90.7184  ],
       [  1.862   , 104.779752],
       [  1.7885  ,  85.275296],
       [  1.7885  ,  81.64656 ],
       [  1.715   ,  83.91452 ],
       [  1.9355  , 104.32616 ],
       [  1.764   ,  81.64656 ],
       [  1.7395  ,  87.089664],
       [  1.8375  , 102.0582  ],
       [  1.8865  ,  92.079176],
       [  1.7885  ,  82.553744],
       [  1.8375  , 111.13004 ],
       [  1.813   ,  97.52228 ],
       [  1.7395  ,  79.3786  ],
       [  1.7885  ,  90.7184  ],
       [  1.813   ,  92.98636 ],
       [  1.862   ,  88.45044 ],
       [  1.8375  ,  95.25432 ],
       [  1.862   ,  86.18248 ],
       [  1.764   ,  81.64656 ],
       [  1.8375  ,  95.25432 ],
       [  1.7885  ,  99.79024 ],
       [  1.715   ,  81.64656 ],
       [  1.715   ,  86.18248 ],
       [  1.7395  ,  83.91452 ],
       [  1.764   ,  83.91452 ],
       [  1.8375  ,  90.7184  ],
       [  1.911   , 106.59412 ],
       [  1.7395  , 113.398   ],
       [  1.7885  ,  95.25432 ],
       [  1.7885  ,  88.45044 ],
       [  1.862   ,  92.98636 ],
       [  1.813   ,  99.79024 ],
       [  1.7885  ,  77.11064 ],
       [  1.764   ,  83.91452 ],
       [  1.7885  ,  99.79024 ],
       [  1.764   ,  81.64656 ],
       [  1.7885  ,  99.79024 ],
       [  1.764   ,  81.64656 ],
       [  1.8375  ,  95.25432 ],
       [  1.8375  ,  97.52228 ],
       [  1.764   ,  96.615096],
       [  1.764   ,  81.64656 ],
       [  1.8865  , 106.59412 ],
       [  1.8865  , 100.697424],
       [  1.8375  ,  95.25432 ],
       [  1.862   , 104.32616 ],
       [  1.96    ,  99.79024 ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  87.996848],
       [  1.813   ,  86.18248 ],
       [  1.8375  , 108.86208 ],
       [  1.7395  ,  89.811216],
       [  1.862   ,  95.25432 ],
       [  1.813   ,  86.18248 ],
       [  1.7885  ,  77.11064 ],
       [  1.7885  ,  81.64656 ],
       [  1.7395  ,  86.18248 ],
       [  1.7885  ,  86.18248 ],
       [  1.7885  ,  79.3786  ],
       [  1.764   ,  92.98636 ],
       [  1.8375  ,  97.52228 ],
       [  1.715   ,  81.64656 ],
       [  1.7395  ,  77.11064 ],
       [  1.764   ,  92.98636 ],
       [  1.8375  , 102.0582  ],
       [  1.7885  ,  81.64656 ],
       [  1.862   , 107.501304],
       [  1.8375  ,  97.52228 ],
       [  1.862   , 106.59412 ],
       [  1.764   ,  86.18248 ],
       [  1.7885  ,  94.347136],
       [  1.8375  ,  95.25432 ],
       [  1.813   ,  86.18248 ],
       [  1.7395  ,  77.11064 ],
       [  1.8865  , 102.0582  ],
       [  1.911   , 104.32616 ],
       [  1.8375  , 102.511792],
       [  1.8375  ,  99.336648],
       [  1.862   , 102.0582  ],
       [  1.764   ,  79.832192],
       [  1.764   ,  81.64656 ],
       [  1.7885  ,  99.79024 ],
       [  1.813   ,  86.18248 ],
       [  1.813   ,  92.98636 ],
       [  1.8375  ,  92.98636 ],
       [  1.7885  ,  95.707912],
       [  1.813   ,  90.7184  ],
       [  1.8865  ,  95.25432 ],
       [  1.911   ,  99.79024 ],
       [  1.911   ,  95.25432 ],
       [  1.813   ,  91.625584],
       [  1.911   , 102.0582  ],
       [  1.813   ,  99.79024 ],
       [  1.764   ,  83.91452 ],
       [  1.862   ,  88.45044 ],
       [  1.7885  ,  99.336648],
       [  1.7885  ,  88.45044 ],
       [  1.8865  ,  99.79024 ],
       [  1.8865  , 106.59412 ],
       [  1.7395  ,  81.64656 ],
       [  1.911   , 104.32616 ],
       [  1.715   ,  86.18248 ],
       [  1.813   ,  86.18248 ],
       [  1.764   ,  90.7184  ],
       [  1.7885  ,  83.460928],
       [  1.8375  ,  90.7184  ],
       [  1.813   ,  99.336648],
       [  1.7885  ,  90.7184  ],
       [  1.813   ,  99.79024 ],
       [  1.7885  ,  72.57472 ],
       [  1.911   ,  90.7184  ],
       [  1.862   ,  97.068688],
       [  1.7885  ,  90.7184  ],
       [  1.8375  ,  81.64656 ],
       [  1.911   , 106.59412 ],
       [  1.8865  , 108.86208 ],
       [  1.764   ,  83.91452 ],
       [  1.6905  ,  74.84268 ],
       [  1.813   ,  83.91452 ],
       [  1.715   ,  77.11064 ],
       [  1.813   ,  95.25432 ],
       [  1.862   ,  92.98636 ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  86.18248 ],
       [  1.7885  ,  72.57472 ],
       [  1.7885  ,  81.64656 ],
       [  1.813   ,  81.64656 ],
       [  1.813   ,  90.7184  ],
       [  1.715   ,  86.18248 ],
       [  1.813   , 102.965384],
       [  1.8375  ,  90.264808],
       [  1.764   ,  83.91452 ],
       [  1.8865  , 108.86208 ],
       [  1.7885  , 102.0582  ],
       [  1.862   , 104.32616 ],
       [  1.7885  ,  90.7184  ],
       [  1.8375  , 111.13004 ],
       [  1.813   ,  86.18248 ],
       [  1.7885  ,  95.25432 ],
       [  1.7395  ,  90.7184  ],
       [  1.862   ,  92.98636 ],
       [  1.8375  ,  95.25432 ],
       [  1.7885  ,  77.11064 ],
       [  1.7885  ,  81.64656 ],
       [  1.862   ,  95.25432 ],
       [  1.7885  ,  93.439952],
       [  1.8375  ,  88.45044 ],
       [  1.8375  ,  90.7184  ],
       [  1.8865  ,  90.7184  ],
       [  1.813   ,  92.98636 ],
       [  1.7395  ,  95.25432 ],
       [  1.813   ,  90.7184  ],
       [  1.813   ,  92.98636 ],
       [  1.8375  ,  86.18248 ],
       [  1.764   ,  92.98636 ],
       [  1.7885  ,  79.3786  ],
       [  1.862   ,  99.79024 ],
       [  1.8865  , 111.13004 ],
       [  1.7885  ,  81.64656 ],
       [  1.715   ,  88.45044 ],
       [  1.7885  ,  97.52228 ],
       [  1.813   ,  81.64656 ],
       [  1.8865  ,  86.18248 ],
       [  1.8375  ,  86.18248 ],
       [  1.7885  ,  95.25432 ],
       [  1.8865  , 115.66596 ],
       [  1.8865  , 104.32616 ],
       [  1.813   ,  92.98636 ],
       [  1.813   ,  97.52228 ],
       [  1.8375  ,  99.79024 ],
       [  1.7395  ,  89.357624],
       [  1.715   ,  84.821704],
       [  1.9355  , 111.13004 ],
       [  1.813   ,  90.7184  ],
       [  1.764   ,  90.7184  ],
       [  2.009   , 104.779752],
       [  1.813   ,  74.84268 ],
       [  1.813   , 103.418976],
       [  1.764   ,  97.52228 ],
       [  1.862   , 115.212368],
       [  1.7885  ,  81.64656 ],
       [  1.764   ,  97.52228 ],
       [  1.764   ,  77.11064 ],
       [  1.715   ,  74.84268 ],
       [  1.7395  ,  77.11064 ],
       [  1.8375  , 101.604608],
       [  1.862   , 108.408488],
       [  1.862   ,  95.25432 ],
       [  1.911   ,  99.79024 ],
       [  1.8375  ,  90.7184  ],
       [  1.862   ,  88.45044 ],
       [  1.764   , 104.32616 ],
       [  1.7885  ,  99.79024 ],
       [  1.715   ,  87.089664],
       [  1.813   ,  92.98636 ],
       [  1.7885  ,  92.98636 ],
       [  1.7885  ,  83.91452 ],
       [  1.8375  ,  92.98636 ],
       [  1.715   ,  81.64656 ],
       [  1.9355  , 108.86208 ],
       [  1.8375  ,  97.52228 ],
       [  1.8375  ,  88.45044 ],
       [  1.7885  ,  97.52228 ],
       [  1.715   ,  88.45044 ],
       [  1.7395  ,  88.45044 ],
       [  1.8375  ,  95.25432 ],
       [  1.764   ,  81.64656 ],
       [  1.764   ,  81.64656 ],
       [  1.862   , 106.59412 ],
       [  1.8375  ,  90.7184  ],
       [  1.6905  ,  81.64656 ],
       [  1.764   ,  92.079176],
       [  1.862   ,  90.7184  ],
       [  1.7395  ,  86.18248 ],
       [  1.8375  ,  77.11064 ],
       [  1.8865  ,  97.52228 ],
       [  1.715   ,  81.64656 ],
       [  1.764   ,  84.821704],
       [  1.7395  ,  81.64656 ],
       [  1.813   ,  95.25432 ],
       [  1.862   ,  87.543256],
       [  1.764   ,  90.7184  ],
       [  1.813   ,  77.11064 ],
       [  1.764   ,  88.45044 ],
       [  1.7395  ,  86.18248 ],
       [  1.715   ,  81.64656 ],
       [  1.764   ,  77.11064 ],
       [  1.813   ,  95.25432 ],
       [  1.813   ,  99.79024 ],
       [  1.8375  ,  95.25432 ],
       [  1.813   , 111.13004 ],
       [  1.7395  , 100.243832],
       [  1.7395  ,  83.91452 ],
       [  1.862   , 104.32616 ],
       [  1.7395  ,  79.3786  ],
       [  1.813   ,  90.7184  ],
       [  1.764   ,  90.7184  ],
       [  1.862   , 113.398   ],
       [  1.911   ,  95.25432 ],
       [  1.764   ,  97.52228 ],
       [  1.862   ,  97.52228 ],
       [  1.715   ,  89.811216],
       [  1.666   ,  75.749864],
       [  1.7395  ,  86.18248 ],
       [  1.8865  ,  97.52228 ],
       [  1.6905  ,  72.57472 ],
       [  1.8375  ,  79.3786  ],
       [  1.8375  ,  86.18248 ],
       [  1.862   , 108.86208 ],
       [  1.764   ,  79.3786  ],
       [  1.8865  , 113.398   ],
       [  1.715   ,  86.18248 ],
       [  1.9355  ,  86.18248 ],
       [  1.813   ,  77.11064 ],
       [  1.666   ,  68.0388  ],
       [  1.8375  ,  99.79024 ],
       [  1.764   , 117.93392 ],
       [  1.764   ,  88.45044 ],
       [  1.7885  ,  86.18248 ],
       [  1.813   ,  81.64656 ],
       [  1.764   ,  88.45044 ],
       [  1.8375  ,  99.336648],
       [  1.764   , 102.0582  ],
       [  1.7885  ,  96.161504],
       [  1.862   ,  86.18248 ],
       [  1.813   ,  96.161504],
       [  1.8375  ,  95.25432 ],
       [  1.862   ,  90.7184  ],
       [  1.813   ,  99.79024 ],
       [  1.764   ,  83.91452 ],
       [  1.7885  , 104.779752],
       [  1.764   ,  83.91452 ],
       [  1.7885  ,  81.64656 ],
       [  1.764   ,  99.79024 ],
       [  1.7885  ,  88.904032],
       [  1.715   ,  72.57472 ],
       [  1.764   ,  92.98636 ],
       [  1.8375  ,  95.25432 ],
       [  1.7885  ,  90.7184  ],
       [  1.862   , 116.573144],
       [  1.8865  ,  92.98636 ],
       [  1.8865  ,  94.347136],
       [  1.8375  ,  97.52228 ],
       [  1.8375  ,  95.25432 ],
       [  1.862   ,  92.079176],
       [  1.764   ,  95.25432 ],
       [  1.7885  ,  90.7184  ],
       [  1.813   ,  92.98636 ],
       [  1.764   ,  86.18248 ],
       [  1.813   , 102.0582  ],
       [  1.813   ,  93.893544],
       [  1.8375  ,  96.161504],
       [  1.7395  ,  95.25432 ],
       [  1.862   ,  86.18248 ],
       [  1.7885  ,  97.52228 ],
       [  1.666   ,  88.904032],
       [  1.764   ,  79.3786  ],
       [  1.6905  ,  79.3786  ],
       [  1.7885  ,  92.98636 ],
       [  1.8375  ,  95.25432 ],
       [  1.813   ,  89.357624],
       [  1.813   , 103.418976],
       [  1.813   ,  86.18248 ],
       [  1.7885  ,  92.532768],
       [  1.813   ,  74.84268 ],
       [  1.8375  ,  97.975872],
       [  1.813   ,  95.25432 ],
       [  1.7885  ,  97.52228 ],
       [  1.862   , 103.872568],
       [  1.911   , 108.86208 ],
       [  1.7885  ,  92.98636 ],
       [  1.8375  , 102.0582  ],
       [  1.6415  ,  81.64656 ],
       [  1.715   ,  73.935496],
       [  1.715   ,  79.3786  ],
       [  1.9355  ,  92.98636 ],
       [  1.862   ,  95.707912],
       [  1.764   ,  81.64656 ],
       [  1.8375  ,  92.98636 ]])

In [ ]:
batsmen.shape

(323, 2)

In [ ]:
bowlers = players_array[skills == 'Bowler']
bowlers

array([[  1.764   ,  95.25432 ],
       [  1.7395  ,  81.64656 ],
       [  1.813   ,  83.91452 ],
       [  1.813   ,  72.57472 ],
       [  1.6905  ,  81.64656 ],
       [  1.8375  ,  83.91452 ],
       [  1.8375  , 108.86208 ],
       [  1.862   ,  90.7184  ],
       [  1.715   ,  84.368112],
       [  1.7885  ,  90.7184  ],
       [  1.862   ,  96.161504],
       [  1.862   , 104.32616 ],
       [  1.666   ,  70.30676 ],
       [  1.8375  , 102.0582  ],
       [  1.666   ,  72.57472 ],
       [  1.813   ,  92.98636 ],
       [  1.813   ,  90.7184  ],
       [  1.9355  ,  92.98636 ],
       [  1.813   , 104.32616 ],
       [  1.862   ,  87.089664],
       [  1.862   ,  90.7184  ],
       [  1.813   ,  88.45044 ],
       [  1.7885  ,  83.91452 ],
       [  1.813   ,  79.3786  ],
       [  1.764   ,  92.532768],
       [  1.813   ,  95.707912],
       [  1.8375  ,  86.18248 ],
       [  1.862   ,  90.7184  ],
       [  1.8375  ,  97.52228 ],
       [  1.764   ,  91.171992],
       [  1.8865  ,  99.79024 ],
       [  1.8375  ,  86.18248 ],
       [  1.7885  ,  81.64656 ],
       [  1.862   ,  88.45044 ],
       [  1.7395  ,  86.18248 ],
       [  1.8865  ,  83.91452 ],
       [  1.7395  ,  86.18248 ],
       [  1.8375  ,  90.7184  ],
       [  1.8375  , 126.098576],
       [  1.9355  ,  97.52228 ],
       [  1.8865  , 104.32616 ],
       [  1.862   , 108.86208 ],
       [  1.7395  ,  83.460928],
       [  1.7395  ,  86.18248 ],
       [  1.764   ,  89.357624],
       [  1.7885  ,  92.532768],
       [  1.764   ,  92.98636 ],
       [  1.8375  ,  90.7184  ],
       [  1.862   ,  77.11064 ],
       [  1.715   ,  86.18248 ],
       [  1.7395  ,  87.543256],
       [  1.813   ,  90.7184  ],
       [  1.6905  ,  78.017824],
       [  1.8375  , 102.0582  ],
       [  1.7885  ,  89.357624],
       [  1.8865  ,  90.7184  ],
       [  1.764   ,  80.285784],
       [  1.7885  ,  90.7184  ],
       [  1.7885  ,  90.7184  ],
       [  1.8375  ,  92.98636 ],
       [  1.7885  ,  97.52228 ],
       [  1.8375  ,  99.79024 ],
       [  1.7885  ,  90.7184  ],
       [  1.764   ,  79.3786  ],
       [  1.764   ,  79.3786  ],
       [  1.813   ,  90.7184  ],
       [  1.8375  ,  88.45044 ],
       [  1.96    , 108.86208 ],
       [  1.764   ,  68.0388  ],
       [  1.813   ,  91.625584],
       [  1.813   ,  90.7184  ],
       [  1.8375  ,  92.98636 ],
       [  1.8375  ,  83.91452 ],
       [  1.7885  ,  91.625584],
       [  1.764   ,  99.79024 ],
       [  1.862   , 106.59412 ],
       [  1.813   ,  81.64656 ],
       [  1.764   ,  90.7184  ],
       [  1.8865  ,  95.25432 ],
       [  1.7885  ,  81.64656 ],
       [  1.715   ,  81.64656 ],
       [  1.764   ,  81.64656 ],
       [  1.911   , 104.32616 ],
       [  1.8375  ,  99.79024 ],
       [  1.862   , 113.398   ],
       [  1.8375  ,  87.089664],
       [  1.764   ,  89.357624],
       [  1.7395  ,  86.18248 ],
       [  1.7885  ,  90.7184  ],
       [  1.764   ,  88.45044 ],
       [  1.764   ,  79.3786  ],
       [  1.764   ,  93.439952],
       [  1.862   , 117.93392 ],
       [  1.862   , 100.243832],
       [  1.7885  ,  92.98636 ],
       [  1.8375  ,  83.91452 ],
       [  1.8375  , 111.13004 ],
       [  1.764   ,  83.91452 ],
       [  1.7885  ,  81.64656 ],
       [  1.7885  ,  95.25432 ],
       [  1.715   ,  88.45044 ],
       [  1.7885  , 108.86208 ],
       [  1.8865  , 113.398   ],
       [  1.8375  ,  95.25432 ],
       [  1.813   ,  81.64656 ],
       [  1.7885  ,  92.98636 ],
       [  1.7885  ,  81.64656 ],
       [  1.8865  ,  99.79024 ],
       [  1.8865  ,  90.7184  ],
       [  1.813   , 102.0582  ],
       [  1.764   ,  83.91452 ],
       [  1.764   ,  83.91452 ],
       [  1.715   ,  79.3786  ],
       [  1.715   ,  95.25432 ],
       [  1.7885  ,  86.636072],
       [  1.8865  ,  90.7184  ],
       [  1.8375  ,  88.45044 ],
       [  1.813   ,  90.7184  ],
       [  1.8865  ,  99.79024 ],
       [  1.862   ,  92.98636 ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  95.25432 ],
       [  1.6905  ,  90.7184  ],
       [  1.7395  ,  83.91452 ],
       [  1.8865  ,  86.18248 ],
       [  1.8375  ,  94.347136],
       [  1.764   ,  81.64656 ],
       [  1.8375  ,  86.18248 ],
       [  1.7885  ,  97.52228 ],
       [  1.8375  , 104.32616 ],
       [  1.8375  ,  94.800728],
       [  1.8865  ,  77.11064 ],
       [  1.715   ,  83.91452 ],
       [  1.7395  ,  86.18248 ],
       [  1.764   ,  72.57472 ],
       [  1.7885  ,  90.7184  ],
       [  1.8375  ,  99.79024 ],
       [  1.813   ,  99.79024 ],
       [  1.813   ,  99.336648],
       [  1.764   ,  81.64656 ],
       [  1.764   ,  86.18248 ],
       [  1.715   ,  83.91452 ],
       [  1.7395  ,  88.45044 ],
       [  1.7885  ,  86.18248 ],
       [  1.7395  ,  83.91452 ],
       [  1.813   , 108.86208 ],
       [  1.7395  ,  81.64656 ],
       [  1.764   ,  88.45044 ],
       [  1.7395  ,  72.57472 ],
       [  1.764   ,  92.98636 ],
       [  1.764   ,  83.91452 ],
       [  1.813   ,  86.18248 ],
       [  1.7885  ,  97.52228 ],
       [  1.8375  ,  70.760352],
       [  1.764   ,  86.18248 ],
       [  1.7395  ,  91.625584],
       [  1.7885  ,  86.18248 ],
       [  1.8375  ,  86.18248 ],
       [  1.764   ,  81.64656 ],
       [  1.764   , 110.676448],
       [  1.7885  ,  90.7184  ],
       [  1.862   , 104.32616 ],
       [  1.862   , 101.151016],
       [  1.813   , 104.32616 ],
       [  1.911   ,  86.18248 ],
       [  1.764   ,  86.18248 ],
       [  1.7395  ,  94.800728],
       [  1.911   ,  90.7184  ],
       [  1.764   ,  90.7184  ],
       [  1.813   ,  88.45044 ],
       [  1.813   ,  86.18248 ],
       [  1.7885  ,  98.883056],
       [  1.7395  ,  86.18248 ],
       [  1.7885  ,  85.275296],
       [  2.009   , 113.398   ],
       [  1.7885  ,  81.64656 ],
       [  1.715   ,  74.84268 ],
       [  1.813   ,  83.91452 ],
       [  1.8375  , 106.59412 ],
       [  1.7395  ,  68.0388  ],
       [  1.813   ,  84.368112],
       [  1.764   ,  89.811216],
       [  1.8375  ,  97.52228 ],
       [  1.8375  ,  81.64656 ],
       [  1.715   ,  87.089664],
       [  1.764   ,  87.089664],
       [  1.862   ,  99.336648],
       [  1.862   ,  99.79024 ],
       [  1.7395  ,  77.11064 ],
       [  1.7395  ,  86.18248 ],
       [  1.764   , 101.151016],
       [  1.7885  ,  85.728888],
       [  1.715   ,  81.64656 ],
       [  1.862   ,  97.52228 ],
       [  1.8375  ,  93.893544],
       [  1.813   ,  83.91452 ],
       [  1.764   ,  86.18248 ],
       [  1.764   ,  94.347136],
       [  1.7395  , 102.0582  ],
       [  1.862   , 108.86208 ],
       [  1.8375  ,  81.64656 ],
       [  1.8375  ,  90.7184  ],
       [  1.911   , 104.32616 ],
       [  1.8375  , 104.32616 ],
       [  1.8375  ,  92.98636 ],
       [  1.8375  ,  86.18248 ]])

In [ ]:
len(bowlers)

206

In [ ]:
keepers = players_array[skills == 'Keeper']
keepers

array([[  1.813   ,  81.64656 ],
       [  1.862   ,  92.98636 ],
       [  1.813   ,  85.275296],
       [  1.7885  ,  81.64656 ],
       [  1.813   ,  90.264808],
       [  1.7885  ,  97.52228 ],
       [  1.813   ,  93.439952],
       [  1.764   ,  85.275296],
       [  1.8865  ,  99.79024 ],
       [  1.813   ,  95.25432 ],
       [  1.715   ,  88.45044 ],
       [  1.911   , 103.418976],
       [  1.8375  , 122.46984 ],
       [  1.813   ,  99.79024 ],
       [  1.6905  ,  81.64656 ],
       [  1.813   , 106.59412 ],
       [  1.813   ,  95.25432 ],
       [  1.7885  ,  90.7184  ],
       [  1.813   , 102.0582  ],
       [  1.7885  ,  83.91452 ],
       [  1.8375  ,  83.91452 ],
       [  1.8375  ,  83.91452 ],
       [  1.813   ,  86.18248 ],
       [  1.862   ,  99.79024 ],
       [  1.862   , 113.398   ],
       [  1.911   ,  95.25432 ],
       [  1.813   ,  90.7184  ],
       [  1.764   ,  87.996848],
       [  1.7395  ,  81.64656 ],
       [  1.8375  ,  90.7184  ],
       [  1.813   ,  93.439952],
       [  1.764   ,  95.707912],
       [  1.715   ,  83.91452 ],
       [  1.813   ,  83.91452 ],
       [  1.764   ,  99.79024 ],
       [  1.715   ,  86.18248 ],
       [  1.7395  ,  75.749864],
       [  1.764   ,  86.18248 ],
       [  1.813   ,  77.11064 ],
       [  1.813   ,  90.7184  ],
       [  1.862   ,  99.79024 ],
       [  1.862   ,  86.18248 ],
       [  1.8375  ,  95.25432 ],
       [  1.7885  ,  86.18248 ],
       [  1.764   ,  99.79024 ],
       [  1.7885  ,  97.52228 ],
       [  1.813   ,  90.7184  ],
       [  1.813   ,  86.18248 ],
       [  1.862   ,  92.98636 ],
       [  1.7885  ,  86.18248 ],
       [  1.8375  ,  79.3786  ],
       [  1.8375  ,  90.7184  ],
       [  1.813   ,  99.336648],
       [  1.911   , 101.151016],
       [  1.813   ,  90.7184  ],
       [  1.813   ,  95.25432 ],
       [  1.7395  ,  88.45044 ],
       [  1.8865  ,  87.996848],
       [  1.862   ,  92.98636 ],
       [  1.7395  ,  87.543256],
       [  1.911   , 112.944408],
       [  1.813   ,  86.18248 ],
       [  1.6905  ,  72.57472 ],
       [  1.6905  ,  81.64656 ],
       [  1.813   , 100.697424],
       [  1.862   , 108.86208 ],
       [  1.7395  ,  90.7184  ],
       [  1.7395  ,  99.79024 ],
       [  1.764   ,  79.3786  ],
       [  1.7885  ,  74.389088],
       [  1.764   ,  81.64656 ],
       [  1.764   ,  77.11064 ],
       [  1.7395  ,  88.45044 ],
       [  1.7885  ,  87.089664],
       [  1.7395  , 101.604608],
       [  1.7885  ,  88.45044 ],
       [  1.7395  ,  79.3786  ],
       [  1.764   ,  81.64656 ],
       [  1.862   , 104.32616 ],
       [  1.8375  ,  88.45044 ],
       [  1.9355  ,  92.98636 ],
       [  1.7885  ,  86.18248 ],
       [  1.8865  , 102.0582  ],
       [  1.8375  ,  92.98636 ],
       [  1.813   ,  81.64656 ],
       [  1.813   , 111.13004 ],
       [  1.7395  ,  90.7184  ],
       [  1.813   ,  95.25432 ],
       [  1.7885  ,  90.7184  ],
       [  1.813   ,  99.79024 ],
       [  1.764   ,  81.64656 ],
       [  1.764   ,  99.79024 ],
       [  1.7395  ,  74.84268 ],
       [  1.7885  ,  88.45044 ],
       [  1.7885  ,  99.79024 ],
       [  1.8865  ,  99.79024 ],
       [  1.8375  ,  92.98636 ],
       [  1.7885  ,  86.18248 ],
       [  1.764   ,  72.57472 ],
       [  1.862   ,  99.79024 ],
       [  1.7885  ,  86.18248 ],
       [  1.862   ,  99.79024 ],
       [  1.8375  , 106.59412 ],
       [  1.6905  ,  76.203456],
       [  1.7885  , 108.86208 ],
       [  1.764   ,  86.18248 ],
       [  1.7395  ,  86.18248 ],
       [  1.764   ,  81.64656 ],
       [  1.8375  , 100.697424],
       [  1.8375  ,  90.7184  ],
       [  1.764   ,  86.18248 ],
       [  1.7395  ,  90.7184  ],
       [  1.666   ,  94.800728],
       [  1.7885  ,  91.625584],
       [  1.862   , 108.86208 ],
       [  1.8375  ,  98.429464],
       [  1.862   , 104.779752],
       [  1.862   , 101.151016],
       [  1.813   ,  99.79024 ],
       [  1.813   , 106.59412 ],
       [  1.813   ,  85.275296],
       [  1.862   , 106.59412 ],
       [  1.8375  ,  97.52228 ],
       [  1.666   ,  81.64656 ],
       [  1.764   ,  83.91452 ],
       [  1.764   ,  95.25432 ],
       [  1.7395  ,  86.18248 ],
       [  1.7395  ,  81.64656 ],
       [  1.8375  ,  94.347136],
       [  1.8865  , 106.59412 ],
       [  1.8865  ,  86.18248 ],
       [  1.813   ,  81.64656 ],
       [  1.8375  , 111.583632],
       [  1.764   ,  90.7184  ],
       [  1.813   ,  90.7184  ],
       [  1.862   , 100.697424],
       [  1.8865  ,  99.79024 ],
       [  1.8865  ,  94.347136],
       [  1.813   ,  77.11064 ],
       [  1.7885  ,  86.18248 ],
       [  1.7885  ,  86.18248 ]])

In [ ]:
len(keepers)

141

In [ ]:
Keeper_Batsmen = players_array[skills == 'Keeper-Batsman']
Keeper_Batsmen

array([[  1.764   ,  95.25432 ],
       [  1.6905  ,  79.832192],
       [  1.7885  ,  85.728888],
       [  1.911   ,  99.336648],
       [  1.813   , 104.32616 ],
       [  1.862   ,  88.45044 ],
       [  1.813   ,  88.45044 ],
       [  1.911   ,  90.7184  ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  90.7184  ],
       [  1.6905  ,  83.91452 ],
       [  1.813   ,  92.98636 ],
       [  1.8375  ,  90.7184  ],
       [  1.862   , 101.604608],
       [  1.911   ,  95.25432 ],
       [  1.813   ,  99.79024 ],
       [  1.8865  ,  90.7184  ],
       [  1.9845  , 117.93392 ],
       [  1.8865  ,  90.7184  ],
       [  1.764   ,  92.98636 ],
       [  1.7885  ,  95.707912],
       [  1.7885  ,  90.7184  ],
       [  1.715   ,  77.11064 ],
       [  1.8375  , 102.0582  ],
       [  1.8375  ,  99.79024 ],
       [  1.862   ,  86.18248 ],
       [  1.813   ,  72.57472 ],
       [  1.8375  , 100.697424],
       [  1.813   ,  99.79024 ],
       [  1.813   ,  88.45044 ],
       [  1.7885  ,  77.11064 ],
       [  1.7885  ,  90.7184  ],
       [  1.764   ,  83.91452 ],
       [  1.813   ,  81.64656 ],
       [  1.813   ,  86.18248 ],
       [  1.911   ,  95.25432 ],
       [  1.7885  ,  81.64656 ],
       [  1.862   ,  99.79024 ],
       [  1.7885  ,  95.25432 ],
       [  1.715   ,  81.64656 ],
       [  1.764   ,  83.91452 ],
       [  1.7395  ,  80.739376],
       [  1.813   ,  90.7184  ],
       [  1.813   ,  95.25432 ],
       [  1.9355  , 131.54168 ],
       [  1.813   ,  99.79024 ],
       [  1.862   ,  77.11064 ],
       [  1.911   ,  99.79024 ],
       [  1.813   ,  90.7184  ],
       [  1.813   , 102.0582  ],
       [  1.764   ,  88.45044 ],
       [  1.813   ,  99.79024 ],
       [  1.715   ,  77.11064 ],
       [  1.8375  ,  88.45044 ],
       [  1.7395  ,  81.64656 ],
       [  1.7885  ,  93.439952],
       [  1.7395  ,  90.7184  ],
       [  1.7885  , 102.0582  ],
       [  1.8375  , 102.0582  ],
       [  1.813   , 105.686936],
       [  1.813   ,  81.64656 ],
       [  1.7885  ,  81.64656 ],
       [  1.813   ,  86.18248 ],
       [  1.7395  ,  74.84268 ],
       [  1.7885  ,  83.91452 ],
       [  1.813   ,  92.98636 ],
       [  1.764   ,  92.98636 ],
       [  1.8375  ,  99.79024 ],
       [  1.764   ,  77.11064 ],
       [  1.8375  ,  88.45044 ],
       [  1.813   , 104.32616 ],
       [  1.8865  , 109.315672],
       [  1.8375  ,  95.25432 ],
       [  1.8375  ,  79.3786  ],
       [  1.862   ,  97.52228 ],
       [  1.7885  ,  89.811216],
       [  1.813   ,  77.11064 ],
       [  1.6905  ,  98.883056],
       [  1.7395  ,  88.45044 ],
       [  1.764   ,  97.52228 ],
       [  1.7885  ,  83.91452 ],
       [  1.813   ,  95.25432 ],
       [  1.813   ,  97.52228 ],
       [  1.8865  ,  90.7184  ],
       [  1.7395  ,  94.347136],
       [  1.8375  , 105.233344],
       [  1.8375  , 104.32616 ],
       [  1.8375  ,  95.25432 ],
       [  1.862   ,  96.161504],
       [  1.764   ,  90.7184  ],
       [  1.96    , 107.501304],
       [  1.715   ,  86.18248 ],
       [  1.764   ,  68.0388  ],
       [  1.7395  ,  99.79024 ],
       [  1.7395  ,  86.18248 ],
       [  1.7395  ,  83.91452 ],
       [  1.8375  ,  86.18248 ],
       [  1.764   ,  95.25432 ],
       [  1.813   ,  88.45044 ],
       [  1.813   ,  88.45044 ],
       [  1.7885  ,  86.18248 ],
       [  1.8375  ,  86.18248 ],
       [  1.8375  ,  81.64656 ],
       [  1.862   ,  84.821704],
       [  1.8375  ,  86.18248 ],
       [  1.764   ,  77.11064 ],
       [  1.764   ,  79.3786  ],
       [  1.813   ,  92.98636 ],
       [  1.813   ,  86.18248 ],
       [  1.715   ,  92.98636 ],
       [  1.7395  ,  86.18248 ],
       [  1.764   ,  97.52228 ],
       [  1.8375  ,  86.636072],
       [  1.7885  ,  82.100152],
       [  1.7395  ,  90.7184  ],
       [  1.715   ,  70.30676 ],
       [  1.8375  ,  95.25432 ],
       [  1.7885  ,  92.98636 ],
       [  1.8375  ,  86.18248 ],
       [  1.7395  ,  72.57472 ],
       [  1.7885  ,  97.52228 ],
       [  1.813   ,  86.18248 ],
       [  1.764   ,  95.25432 ],
       [  1.813   ,  83.91452 ],
       [  1.813   ,  99.79024 ],
       [  1.8375  ,  99.79024 ],
       [  1.764   ,  79.3786  ],
       [  1.7885  ,  90.7184  ],
       [  1.764   , 103.872568],
       [  1.764   ,  93.439952],
       [  1.764   ,  81.64656 ],
       [  1.7395  ,  88.45044 ],
       [  1.8375  ,  85.275296],
       [  1.813   , 104.32616 ],
       [  1.7885  ,  86.18248 ],
       [  1.9355  ,  86.18248 ],
       [  1.813   , 106.140528],
       [  1.813   ,  83.91452 ],
       [  1.8375  ,  99.79024 ],
       [  1.7885  ,  80.285784],
       [  1.7395  ,  79.3786  ],
       [  1.813   ,  95.25432 ],
       [  1.9355  ,  94.347136],
       [  1.764   ,  72.57472 ],
       [  1.8375  ,  99.79024 ],
       [  1.715   ,  77.11064 ],
       [  1.715   ,  70.30676 ],
       [  1.7395  ,  90.7184  ],
       [  1.862   ,  99.79024 ],
       [  1.862   , 103.418976],
       [  1.764   ,  83.460928],
       [  1.764   ,  81.64656 ],
       [  1.6905  ,  79.832192],
       [  1.7885  ,  72.57472 ],
       [  1.813   ,  95.707912],
       [  1.862   ,  83.91452 ],
       [  1.813   ,  83.91452 ],
       [  1.8375  ,  92.98636 ],
       [  1.764   ,  77.11064 ],
       [  1.7395  ,  91.171992],
       [  1.813   ,  99.79024 ],
       [  1.7885  ,  79.3786  ],
       [  1.7885  ,  90.7184  ],
       [  1.862   ,  99.79024 ],
       [  1.8375  ,  99.79024 ],
       [  1.96    , 108.86208 ],
       [  1.862   ,  77.11064 ],
       [  1.8865  ,  90.7184  ],
       [  1.7885  ,  97.52228 ],
       [  1.6905  ,  79.3786  ],
       [  1.813   , 104.32616 ],
       [  1.813   ,  81.64656 ],
       [  1.7885  ,  86.18248 ],
       [  1.813   ,  99.79024 ],
       [  1.813   ,  90.7184  ],
       [  1.7885  ,  95.25432 ],
       [  1.764   ,  85.275296],
       [  1.7885  , 102.0582  ],
       [  1.813   ,  95.25432 ],
       [  1.862   ,  96.615096],
       [  1.7885  , 113.398   ],
       [  1.813   ,  86.18248 ],
       [  1.7885  , 105.233344],
       [  1.813   ,  99.79024 ],
       [  1.813   ,  81.64656 ],
       [  1.7395  ,  81.64656 ],
       [  1.862   ,  90.7184  ],
       [  1.862   ,  89.811216],
       [  1.9355  , 108.86208 ],
       [  1.7885  ,  83.91452 ],
       [  1.7885  ,  77.11064 ],
       [  1.8375  , 104.32616 ],
       [  1.8375  ,  95.25432 ],
       [  1.7395  ,  83.91452 ],
       [  1.7395  ,  88.45044 ],
       [  1.764   ,  91.625584],
       [  1.764   ,  81.64656 ],
       [  1.911   , 108.86208 ],
       [  1.862   ,  92.98636 ],
       [  1.813   ,  91.171992],
       [  1.8865  , 104.32616 ],
       [  1.7885  ,  88.45044 ],
       [  1.862   ,  99.79024 ],
       [  1.7395  ,  86.18248 ],
       [  1.813   ,  92.532768],
       [  1.6905  ,  77.11064 ],
       [  1.715   ,  83.91452 ],
       [  1.764   ,  79.3786  ],
       [  1.813   ,  95.25432 ],
       [  1.7885  ,  86.18248 ],
       [  1.764   ,  89.357624],
       [  1.8375  ,  92.98636 ],
       [  1.96    , 113.398   ],
       [  1.8865  ,  90.7184  ],
       [  1.9355  ,  90.7184  ],
       [  1.7885  ,  93.439952],
       [  1.862   ,  97.52228 ],
       [  1.7885  ,  85.275296],
       [  1.8375  , 104.32616 ],
       [  1.715   ,  88.45044 ],
       [  1.764   ,  90.7184  ],
       [  1.715   ,  85.728888],
       [  1.7885  ,  86.18248 ],
       [  1.862   ,  90.7184  ],
       [  1.9355  ,  86.18248 ],
       [  1.764   ,  83.91452 ],
       [  1.862   ,  79.3786  ],
       [  1.764   ,  97.52228 ],
       [  1.7395  ,  95.25432 ],
       [  1.8865  ,  99.79024 ],
       [  1.862   ,  92.98636 ],
       [  1.862   ,  95.25432 ],
       [  1.7885  ,  99.79024 ],
       [  1.7885  ,  86.18248 ],
       [  1.764   ,  84.368112],
       [  1.7395  ,  81.64656 ],
       [  1.764   ,  86.18248 ],
       [  1.764   ,  95.25432 ],
       [  1.764   ,  90.7184  ],
       [  1.8865  ,  95.25432 ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  90.7184  ],
       [  1.862   , 108.86208 ],
       [  1.764   ,  77.11064 ],
       [  1.8865  ,  99.79024 ],
       [  1.7885  ,  95.25432 ],
       [  1.715   ,  74.84268 ],
       [  1.7885  ,  94.347136],
       [  1.8865  ,  92.98636 ],
       [  1.9845  , 104.32616 ],
       [  1.764   ,  90.7184  ],
       [  1.813   ,  80.285784],
       [  1.862   ,  95.25432 ],
       [  1.7885  ,  77.11064 ],
       [  1.7395  ,  90.7184  ],
       [  1.813   ,  99.79024 ],
       [  1.764   ,  77.11064 ],
       [  1.7885  ,  83.007336],
       [  1.7395  ,  87.089664],
       [  1.7395  ,  81.64656 ],
       [  1.813   ,  81.64656 ],
       [  1.764   ,  92.98636 ],
       [  1.862   ,  77.11064 ],
       [  1.813   ,  88.904032],
       [  1.764   ,  75.749864],
       [  1.8375  ,  88.45044 ],
       [  1.7395  ,  72.57472 ],
       [  1.8865  , 102.0582  ],
       [  1.764   ,  95.25432 ],
       [  1.715   ,  79.832192],
       [  1.764   ,  83.460928],
       [  1.764   ,  88.45044 ],
       [  1.813   ,  91.625584],
       [  1.764   ,  83.91452 ],
       [  1.8375  ,  94.800728],
       [  1.8375  , 103.418976],
       [  1.8375  ,  95.25432 ],
       [  1.862   ,  95.25432 ],
       [  1.8375  ,  97.975872],
       [  1.8375  ,  90.7184  ],
       [  1.7395  ,  95.25432 ],
       [  1.715   ,  99.79024 ],
       [  1.8375  ,  88.45044 ],
       [  1.813   ,  90.7184  ],
       [  1.715   ,  92.98636 ],
       [  1.862   ,  90.7184  ],
       [  1.813   ,  77.11064 ],
       [  1.764   ,  97.52228 ],
       [  1.813   , 110.676448],
       [  1.7885  ,  83.91452 ],
       [  1.911   , 104.32616 ],
       [  1.7885  ,  90.7184  ],
       [  1.7885  ,  86.18248 ],
       [  1.7885  ,  81.64656 ],
       [  1.862   , 104.32616 ],
       [  1.8375  , 101.604608],
       [  1.7885  ,  80.739376],
       [  1.7885  ,  83.91452 ],
       [  1.813   ,  81.64656 ],
       [  1.7885  ,  86.18248 ],
       [  1.7885  ,  86.18248 ],
       [  1.8375  ,  99.79024 ],
       [  1.764   ,  90.7184  ],
       [  1.8375  ,  77.11064 ],
       [  1.764   ,  77.11064 ],
       [  1.7395  ,  77.11064 ],
       [  1.862   ,  86.18248 ],
       [  1.8375  , 104.32616 ],
       [  2.0335  , 117.93392 ],
       [  1.862   ,  95.25432 ],
       [  1.8865  , 111.13004 ],
       [  1.764   ,  87.089664],
       [  1.813   ,  90.7184  ],
       [  1.7395  ,  84.368112],
       [  1.715   ,  77.11064 ],
       [  1.7395  ,  89.357624],
       [  1.813   ,  93.893544],
       [  1.8375  , 102.0582  ],
       [  1.813   ,  95.25432 ],
       [  1.8865  , 104.32616 ],
       [  1.813   ,  90.7184  ],
       [  1.8375  , 107.954896],
       [  1.8865  , 106.140528],
       [  1.813   ,  90.7184  ],
       [  1.764   ,  77.11064 ],
       [  1.7395  ,  99.79024 ],
       [  1.8375  ,  95.25432 ],
       [  1.715   ,  81.64656 ],
       [  1.8375  ,  99.79024 ],
       [  1.7885  ,  94.347136],
       [  1.813   ,  88.45044 ],
       [  1.8375  ,  90.7184  ],
       [  1.7885  ,  83.91452 ],
       [  1.6415  ,  74.84268 ],
       [  1.813   ,  99.79024 ],
       [  1.7885  ,  96.161504],
       [  1.8375  ,  97.52228 ],
       [  1.764   ,  92.98636 ],
       [  1.8865  ,  95.25432 ],
       [  1.911   ,  94.347136],
       [  1.813   ,  97.52228 ],
       [  1.6905  ,  86.18248 ],
       [  1.8375  ,  99.79024 ],
       [  1.813   ,  81.64656 ],
       [  1.7885  ,  88.45044 ]])

In [ ]:
Keeper_Batsmen.size

690

In [ ]:
# working with CSV file
import pandas as pd # pd.Series is 1D and pd.DataFrame it more like a table
cars = pd.read_csv('cars.csv')
cars

    USCA   US United States    809  FALSE
0  ASPAC  AUS     Australia  731.0   True
1  ASPAC  JAP         Japan  588.0   True
2  ASPAC   IN         India   18.0   True
3  ASPAC   RU        Russia  200.0  False
4  LATAM  MOR       Morocco   70.0  False
5    AFR   EG         Egypt   45.0  False
6    EUR  ENG       England    NaN   True

In [ ]:
type(cars)

pandas.core.frame.DataFrame

In [ ]:
cars_df = pd.read_csv('cars.csv', header = None)
cars_df

       0    1              2      3      4
0   USCA   US  United States  809.0  False
1  ASPAC  AUS      Australia  731.0   True
2  ASPAC  JAP          Japan  588.0   True
3  ASPAC   IN          India   18.0   True
4  ASPAC   RU         Russia  200.0  False
5  LATAM  MOR        Morocco   70.0  False
6    AFR   EG          Egypt   45.0  False
7    EUR  ENG        England    NaN   True

In [ ]:
cars_df.columns

Index([0, 1, 2, 3, 4], dtype='int64')

In [ ]:
cars.columns

Index(['USCA', 'US', 'United States', '809', 'FALSE'], dtype='object')

In [ ]:
# NAN = Not a Number
# na = Not available

In [ ]:
cars_df = pd.read_csv("cars.csv", header = None, index_col = 0)
cars_df

         1              2      3      4
0
USCA    US  United States  809.0  False
ASPAC  AUS      Australia  731.0   True
ASPAC  JAP          Japan  588.0   True
ASPAC   IN          India   18.0   True
ASPAC   RU         Russia  200.0  False
LATAM  MOR        Morocco   70.0  False
AFR     EG          Egypt   45.0  False
EUR    ENG        England    NaN   True

In [ ]:
cars_df.index.name = 'Country_code'
cars_df

                1              2      3      4
Country_code
USCA           US  United States  809.0  False
ASPAC         AUS      Australia  731.0   True
ASPAC         JAP          Japan  588.0   True
ASPAC          IN          India   18.0   True
ASPAC          RU         Russia  200.0  False
LATAM         MOR        Morocco   70.0  False
AFR            EG          Egypt   45.0  False
EUR           ENG        England    NaN   True